lib/utils.c

`The gethostbyname*() functions are obsolete; with the advent of IPv6, recent applications use getaddrinfo() instead.`
Patch created because of CVE-2015-0235 GHOST: glibc gethostbyname buffer overflow.
I'm not 100% sure if this is correct for the 3 cases that it's used for right now. I created a small script to test output and it's the same. Compiling also worked and keepalived is able to run.

getaddrinfo should be used instead of gethostbyname

---

keepalived/check/check_daemon.c
keepalived/check/check_http.c
keepalived/check/ipvswrapper.c
keepalived/check/ipwrapper.c
keepalived/include/check_data.h
keepalived/include/ipvswrapper.h
keepalived/include/ipwrapper.h

These issues are fixed:
- infinitely repeating logging of an HTTP real server timed-out
- quorum < hysteresis: wrong comparison result
- vs_groups lose quorum on config reload
- adding existing RS to a new vs group item on config reload

A bunch of fixes to the ipvs part

---

keepalived/core/smtp.c

Otherwise we are stuck in an infinite loop around read() returning 0.

smtp: fix infinite loop when the server unexpectedly closes the connection

---

keepalived/include/vrrp_if.h
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_netlink.c

When using VMAC and running multiple instances on the same interface, only one of the VMAC interfaces will get its status flag synched.
This commit will update the status flag for _all_ VMAC interfaces attached to a base interface.

vrrp: sync status flag (up/down) for _all_ VMAC interfaces

---

keepalived/core/snmp.c

The default location should be `/var/agentx/master` (as per RFC2741 and
this is also the default for NetSNMP, including on Debian-based
distributions). This default location is set at configure-time for
NetSNMP and subagent will use it automatically (it is also available
through `net-snmp-config.h`).
A useful feature would be to have a flag to change that if the user
change this settings in the master agent. This commit just reverts this
change to let SNMP subsystem work as expected for most users.
Signed-off-by: Vincent Bernat <vincent@bernat.im>

snmp: don't hardcode AgentX socket location

---

configure.in

With a lazy linker, `libnetsnmpmibs` may require some additional
libraries to be linked (like `libsensors`). Therefore, only rely on
`net-snmp-config` to get the appropriate flags.
Also add some additional tests:
- check that we can build a simple executable (NetSNMP can be quite
broken and in this case, the error during compilation is not crystal
clear, checking that in configure is more informative)
- check if we subagent support is compiled in (This is optional and
again, the error is not crystal clear during compilation).
- check that net-snmp/agent/util_funcs.h is present (Due to a flaw in
NetSNMP build process, this header was not installed for quite a long
time, notably on RHEL derivatives; code to handle its absence was
already present in Keepalived).
This code is derived from the …

snmp: restore use of net-snmp-config to build SNMP support

---

keepalived/check/check_daemon.c
keepalived/core/global_data.c
keepalived/include/global_data.h
keepalived/vrrp/vrrp_daemon.c

This patch will defer setting the global data default values until
after the config file has been parsed. This will potentially avoid two
calls to getaddrinfo. For example, if the router_id and/or email_from
parameters are set in the config file, there is no need to call
getaddrinfo twice in order to set a default value. Instead, this patch
will check to see if they values are unset after parsing the config
file. Note that email_from and smtp_connection_to are only set to a
default value if they are unitialized and smtp_server is specified.

Set global data default values after parsing config file

---

keepalived/vrrp/vrrp.c

In the VRRPv3 code enhancement the ability to check VRRPv2 checksums
was mistakenly removed. This commit adds the functionality back into the
code base.

Re-enable VRRPv2 checksum on inbound pkts

---

keepalived/vrrp/vrrp_ipaddress.c

When vrrp has an IPv4 VIP that matches the primary interface
address, when the VIP is removed from the interface, the original
address ends up getting removed instead of the VIP.
The kernel receives a netlink message instructing it to remove
address x from a particular interface. For IPv4, address x can
be configured multiple times providing the prefix lengths differ.
If the IFA_ADDRESS attribute is not specified in a RTM_DELADDR
message, the kernel will delete the first address it finds a
match on, prefix length is not taken into account.
This fix therefore adds the IFA_ADDRESS attribute when deleting
IPv4 addresses so that the address removed is actually the VIP.

Fix vrrp removes incorrect IPv4 address when VIPs are removed

---

lib/utils.h

* Add missing sys/types.h include to provide u_short type under musl
Signed-off-by: Jo-Philipp Wich <jow@openwrt.org>
Signed-off-by: Nicolas Thill <nico@openwrt.org>

fix build failure with musl libc

---

lib/parser.c

Avoided leaked useless memory in `read_conf_file` and fixed parameter of `memset` in `read_line`.

Avoided leaked useless memory

---

lib/memory.c
lib/memory.h

Its effect is just the same as `free()`. Setting `p` to `NULL` is
useless as this parameter is passed by value. To work as expected, it
should have been a macro.
Given the comment in the function, I think in the past it did something else (memset maybe?). I can also convert it to a macro if needed (so that `p = NULL` has an effect).

memory: get rid of `xfree()`

---

Makefile.in

Current git wants to install MIB always even when built without SNMP support.
This patch fixes this behaviour.

Only install MIBs when built with snmp.

---

Makefile.in

I feel really stupid for letting this slip in.

Makefiles should use tabs, not spaces.

---

doc/man/man5/keepalived.conf.5
keepalived/check/check_data.c
keepalived/check/check_http.c
keepalived/check/check_misc.c
keepalived/check/check_parser.c
keepalived/check/check_snmp.c
keepalived/check/check_ssl.c
keepalived/check/check_tcp.c
keepalived/check/ipvswrapper.c
keepalived/check/ipwrapper.c
keepalived/include/check_data.h
keepalived/include/check_http.h
keepalived/include/check_tcp.h
keepalived/include/ipvswrapper.h
keepalived/include/ipwrapper.h
lib/scheduler.c
lib/timer.c
lib/timer.h

Hi, Alexandre.
Please consider these changes:
1. Http retry logic refined, tcp retry feature added
2. ipvs reflector respects kernel result code
3. fix re-adding RS caused by rs weight change on reload
4. ip family config option for a fwmak service
5. Some minor optimizations around scheduler

changes to ipvs checkers

---

keepalived/core/smtp.c

Fixed the error in function `build_to_header_rcpt_addrs` at `keepalived/core/smtp.c`.

fixed error in building To-header in email

---

doc/keepalived.conf.SYNOPSIS

A new vrrp 'timeout' parameter was added in version 1.2.6 (Git
commit: 019ad5b3a3e4a21a36ca570d370bbaaa34536283 ) but not documented
in the big keepalived.conf.SYNOPSIS example file.

Added vrrp 'timeout' to synopsis

---

doc/KEEPALIVED-MIB
keepalived/vrrp/vrrp_snmp.c

Hi Alexandre,
This pull requests cleans up KEEPALIVED-MIB so that it passes smilint and makes some changes to vrrp_snmp_route() in vrrp_snmp.c. vrrp_snmp_route() was returning the address of the pointer instead of the IP address / network address for dst, gw, gw2, and src. 
Best Regards,
Chris Riley

SNMP fixes/cleanup

---

.gitignore
configure
configure.in
keepalived/check/check_http.c
keepalived/include/ipvswrapper.h
keepalived/include/vrrp.h
keepalived/include/vrrp_if.h
keepalived/include/vrrp_if_config.h
keepalived/vrrp/Makefile.in
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_if_config.c
keepalived/vrrp/vrrp_netlink.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_vmac.c

The following series of patches resolve a number of issues regarding
the use of macvlans with vrrp. Some of the other patches fix typos
that were noticed during investigating the other fixes.
Principally, the patches change some of the ioctls that are called,
and some of the parameters that are passed, set the necessary options
in /proc/sys/net/ipv4/conf automatically, and restore them on exit,
and re-order the closedown sequence.
The end result of the patches is that keepalived starts up and
closes down without any error messages, and there is no need for
external intervention to set the configuration on the vmac or
physical interfaces.
The explicit call of IGMP_DROP_MEMBERSHIP at closedown is also removed, since the kernel handles that when the interface is deleted.

Fix socket and interface setup and closedown code for IPv4 multicast

---

keepalived/include/vrrp_netlink.h
keepalived/vrrp/vrrp_if_config.c
keepalived/vrrp/vrrp_netlink.c

An error was found with the patch to set interface parameters, when using libnl3, and this corrects it.
Also fix "Netlink: filter function error" message on interface creation/deletion.

Fix interface parameter setting with libnl3 and error message on interface creation/deletion

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
doc/man/man8/keepalived.8
doc/samples/keepalived.conf.misc_check
doc/samples/keepalived.conf.misc_check_arg
doc/samples/keepalived.conf.vrrp.lvs_syncd
keepalived/check/check_parser.c
keepalived/check/check_snmp.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/etc/keepalived/keepalived.conf
keepalived/include/check_api.h
keepalived/include/check_data.h
keepalived/include/global_data.h
keepalived/include/vrrp_netlink.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_netlink.c
keepalived/vrrp/vrrp_print.c
keepalived/vrrp/vrrp_scheduler.c

These patches update the man pages to include all configuration parameters and document the signals, removes some residual code left over from removing support for Linux ver 2.2, and makes some vrrp parameter defaults configurable at the global level.
Finally, one patch removes the use of the deprecated nl_join_groups() which I introduced to quickly resolve a problem with using libnl3.

Documentation updates, removal of redundant code, global config

---

keepalived/vrrp/vrrp_ndisc.c

This is necessary in order to prevent the IPv6 stack on a node that
receives the unsolicited and overriding neighbour advertisement for the
VIP (that gets sent automatically when Keepalived transitions to MASTER
state) from immediately removing the VIP from its list of default
routers. See https://bugs.launchpad.net/bugs/1520517 for an example of
the problems this can cause.
Note that the approach in this patch simply unconditionally sets the
router flag. That is better than having it unconditionally unset (VRRP
stands for Virtual *Router* Redundancy Protocol, after all), but it
might not be appropriate whenever VRRP is used to fail over addresses
that are used for other tasks than being routers. Thus it might be
better to read in the interface's "forwarding" sysctl and set the router …

vrrp: set router flag in neighbour advertisements

---

keepalived/check/ipwrapper.c

It may happen that a VS is configured without any RS causing the check thread to segfault when accessing the RS data.
This patches fixes this issue.

check: segfault when there is no real server for a virtual server.

---

keepalived/include/vrrp_netlink.h
keepalived/vrrp/vrrp_netlink.c

When a tracked interface is deleted then recreated with the same config
VRRP groups tracking this interface will remain down. This is due to
tracking of stale information.
This patch listens for netlink messages for the creation of interfaces
and does one of two things.
i) If the interface doesn't exist in the vrrp interface list a new
interface structure is created and the information from the message is
used to fill the structure. This new interface is then added to the
interface queue.
ii) If the interface already exists in the queue we zero it and then
use the information in the message to fill the structure.
Signed-off-by: Anthony Dempsey <adempsey@brocade.com>

Dynamic addition of interfaces from netlink msg

---

lib/notify.c
lib/signals.c

Commit 223ee0d introduced a problem with invoking notify scripts,
and also responding to SIGHUP. These are now resolved.

Fix reloading and invoking notify scripts

---

configure.in

Without it, this error is produced during the build step.
```
In file included from vrrp_daemon.c:28:
../include/vrrp_netlink.h:37:39: error: libnfnetlink/libnfnetlink.h: No such file or directory
make[2]: *** [vrrp_daemon.o] Error 1
```

Added check for libnfnetlink header during the configure step.

---

keepalived/vrrp/vrrp_iptables.c

With apologies for not have spotted the problem. I though I had tested it.

Fix compilation when ipsets not installed

---

configure
configure.in
keepalived/vrrp/vrrp.c

Commit b46dec58fa failed to check the the VIP list existed before
checking how many entries were in the list.
This commit also defaults the address family to IPv4 if no VIPs are
specified.

Fix VRRP respawning when no VIPs specified

---

keepalived/vrrp/vrrp_snmp.c

Commit 2da11f99 introduced defines for ip_rule directions rather
than using strings, but the commit omitted to update the snmp code
when processing the directions.

Fix ip_rule direction for SNMP

---

doc/man/man5/keepalived.conf.5

This 'include' keyword exists since release 1.1.14 (2007-09-13), it's time to document it.

add a line about the 'include' keyword in keepalived.conf(5)

---

keepalived/vrrp/vrrp_iproute.c
keepalived/vrrp/vrrp_iprule.c

Allow routes and rules to use tables >= 256

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/smtp.c
keepalived/include/global_data.h
keepalived/vrrp/vrrp.c

Issue #199 identified that keepalived could be very slow to start up
if DNS queries resolving the local host name were very slow.
keepalived could call get_local_name() twice at startup for each of the
vrrp and checker threads, in order to get the router_id and also the
set the default email_from address, unless these were manually configured.
It also called getaddrinfo() for the local host name every time it sent an
email, in order to set the HELO string.
This commit reduces the total number of calls per thread to one, using
the returned name to set the router_id, email_from address and the HELO
name (which is now saved for reuse every time an email is sent).
In order to allow no DNS lookups to be made, an extra global configuration
parameter is introduced, smtp_helo_name, so that if …

Reduce number of calls to getaddrinfo() reducing DNS lookups

---

doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c

Commit 9d028ac introduced a double free in certain configuration
circumstances, which this resolves.
This commit also changes the malloc() introduced in that commit
to MALLOC().

Stop double free introduced in commit 9d028ac

---

Makefile.in
genhash/Makefile.in
keepalived/Makefile.in
keepalived/check/Makefile.in
keepalived/check/check_daemon.c
keepalived/core/Makefile.in
keepalived/core/main.c
keepalived/libipvs-2.4/Makefile.in
keepalived/vrrp/Makefile.in
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_if.c
lib/.gitignore
lib/Makefile.in
lib/config.h.in
lib/scheduler.c
lib/scheduler.h

These commits make the parent process wait for the child processes to terminate, and reports the termination reason if they don't exit with status 0, and also if keepalived is not built from a released version it reports the git commit from which the code was built.
The purpose of these commits principally relates to issue #159 - VIPs not being removed - where it may be caused by the vrrp child process terminating before completing its closedown processing, but also for any future bug reports where it is useful to know exactly what code version is being run.

Better logging of shutdown process and version of code being run

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/check_daemon.c
keepalived/check/check_parser.c
keepalived/check/ipvswrapper.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/include/global_data.h
keepalived/include/ipvswrapper.h
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_netlink.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_print.c
keepalived/vrrp/vrrp_scheduler.c
keepalived/vrrp/vrrp_snmp.c
lib/parser.c

The main change is to change the lvs_syncd configuration to be global rather than against a vrrp instance, due to confusion that has existed regarding configuring lvs_sync_daemon_if on multiple vrrp instances. Configuration against vrrp instances is still supported but logged as deprecated.
This should satisfy the request for clarification re configuring lvs_sync_daemon in issue #237.
Restarting following an abnormal termination of keepalived now tidies up any residue ipvs and lvs syncd configuration, and also the syncid can be configured but defaults to the vrid as before.

Configure LVS syncd at global level, a few other lvs syncd changes and three minor fixes

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/main.c
keepalived/include/global_data.h
keepalived/include/vrrp.h
keepalived/include/vrrp_scheduler.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_print.c
keepalived/vrrp/vrrp_scheduler.c
lib/parser.c
lib/parser.h

Issue #277 identified that only one set of gratuitous ARP messages was sent after receiving a lower priority advert, whereas two sets would be sent, if configured, after transition to master.
These commits allow the sending of a second set of gratuitous ARP messages, and the configuration of that and resolve issue #277.

Allow sending second set off gratuitous ARP messages after receiving lower priority advert

---

doc/keepalived.conf.SYNOPSIS
keepalived/include/vrrp.h
keepalived/vrrp/vrrp_data.c
lib/Makefile.in

Unfortunately all my systems worked with the previous version of lib/Makefile.in, but I have replaced all the [[ ]] constructs with [ ] and also $(cmd) constructs with `cmd`. I have also replace the =~.

Attempt to fix build breakage

---

Makefile.in

It appears that the condition in Makefile.in for installing VRRP-MIB
was using a non-existent macro, SNMP_RFC2_SUPPORT. This patch removes
two conditions from Makefile.in that use undefined macros and adds a
condition to install VRRP-MIB when SNMP_RFCV2_SUPPORT is set
appropriately.

Install VRRP-MIB when applicable

---

doc/keepalived.conf.SYNOPSIS

Apr 22 18:09:27 localhost Keepalived_vrrp[22943]: VRRP Error : VRID not valid !
Apr 22 18:09:27 localhost Keepalived_vrrp[22943]:              must be between 1 & 255. reconfigure !
Apr 22 18:08:08 localhost Keepalived_vrrp[22843]: (VI_1): Priority not valid! must be between 1 & 255. Reconfigure !

Updated range for virtual_router_id and priority in doc/keepalived.conf.SYNOPSIS

---

keepalived/core/global_parser.c

This may not be the best way of resolving the problem, but it does work.
I will have a think to see if there is a better way of fixing this, and if so I will submit a further patch. It may be that inet_stosockaddr() shouldn't modify the string passed to it (or restore it if it does modify it), and I'll have a look to see what implications that might have.
This resolves issue #309

Allow smtp_server domain names with '-' characters to be parsed correctly

---

configure
configure.ac

The check for macvlan support in the configure script includes
<bits/sockaddr.h>. As this header file doesn't exist in musl libc,
macvlan detection fails.
Additionally, a comment in glibc's <bits/sockaddr.h> says never to
include it directly, but to use <sys/socket.h> instead.
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>

configure: fix macvlan detection with musl libc

---

keepalived/vrrp/vrrp.c

Otherwise, since we use RAW sockets, we will receive IPPROTO_VRRP
packets that come in on any interface.

Bind read sockets to particular interface

---

genhash/layer4.c
keepalived/core/layer4.c
keepalived/core/main.c
keepalived/include/vrrp_scheduler.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_netlink.c
keepalived/vrrp/vrrp_scheduler.c
keepalived/vrrp/vrrp_snmp.c
lib/signals.c

This pull request enhances and supersedes pull request #319.
The original commit removed initialisation of 3 fields of struct msghdr, which are reinstated in commit eaabcc1.
Commit 4239ede extends the idea of the original commit, and updates all other structure initialisations to use field names.

Initialise structs by member names

---

keepalived/vrrp/vrrp_if.c

vrrp/vrrp_if.c: Fix build without VRRP VMAC.

---

doc/KEEPALIVED-MIB
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_scheduler.c

The main commit is the penultimate one (fix preempt delay), which resolves the issue of preempt_delay and nopreempt being ignored when transitioning out of fault state.
While investigating the issue, a number of other issues were found relating to state changes following receiving adverts, and included are commits relating to those issues.
This pull request should resolve issue #296.

Fix preempt issue from fault state

---

keepalived/vrrp/vrrp_print.c

This fixes crashes when running keepalived under SELinux enforcing mode,
which does not allow keepalived proccess to write to /tmp by default.

Check for errors when opening VRRP data and stats files.

---

keepalived/vrrp/vrrp_ipaddress.c

For IPv4 vIPs keepalived adds a /32 to the underlying interface. If
this address matches an address already configured, e.g. a /24, when
this vIP is eventually removed due to a configuration change or
keepalived shutdown, the original address matching the vIP, outside
of keepalived's control, is removed instead. This behaviour is
incorrect. The /32 added by keepalived should be the address being
removed. Keepalived should not be touching any addresses it does not
create.
This commit re-instates d80c171 which was removed in ef73279. The
IFA_ADDRESS attribute is included in the netlink delete address
message so that the /32 keepalived added is removed instead of the
pre-existing interface address.

Fix IPv4 vIP removal when addr matches pre-existing interface addr

---

keepalived/check/check_daemon.c

"ipwrapper.h" and "ipvswrapper.h" are already included on lines 23 and 24

Remove double includes in check_daemon.c

---

configure
configure.ac
genhash/http.c
keepalived/check/check_daemon.c
keepalived/core/main.c
keepalived/include/vrrp_if.h
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_vmac.c
lib/bitops.h
lib/memory.c
lib/memory.h
lib/parser.c
lib/scheduler.c
lib/utils.c
lib/utils.h
lib/vector.c
lib/vector.h

This resolves a segfault reported in issue #365, caused by referencing memory that has been freed and re-alloc'd.
I believe there is still a further cause of a segfault, in thread_child_handler(), but it seems to occur less frequently that the segfault which is fixed here. See issue #365 for further details.

Resolve a segfault when reloading keepalived with vmacs

---

keepalived/check/check_daemon.c
keepalived/core/main.c
keepalived/include/vrrp.h
keepalived/vrrp/vrrp_daemon.c
lib/memory.c
lib/scheduler.c
lib/scheduler.h

This resolves the second cause of a segfault reported in issue #365, caused by referencing memory that has since been freed and re-alloc'd.
This should resolve issue #365.

Resolve a segfault when reloading keepalived

---

doc/KEEPALIVED-MIB
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/check_daemon.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/snmp.c
keepalived/include/global_data.h

This will resolve issue #363 when a second instance of keepalived running was removing and LVS config setup by an currently running instance of keepalived.

Add configuration option to flush LVS configuration

---

keepalived/vrrp/vrrp_data.c

global_data->vrrp_garp_refresh was not propagating into vrrp->garp_refresh

Fix unused global vrrp_garp_master_refresh

---

keepalived/check/ipwrapper.c

Hi,
Some background: have a VS with some RS. One or more RS has it’s health-check failing. In my case, I’m using TCP checks, one of the RS is down, so TCP handshake is failing.
Now reload the configuration. In `clear_diff_rs function`, the RS state is reported: `new_rs->alive = rs->alive;`. But if the RS is failing, the list of checks failing is not copied.
This is a problem, because in checkers, the failed checker of the RS is put back up only if it was previously recorded as down. See [svr_checker_up](https://github.com/acassen/keepalived/blob/master/keepalived/check/ipwrapper.c#L463) and [tcp_epilog](https://github.com/casta/keepalived/blob/master/keepalived/check/check_tcp.c#L118) for example.
So the consequence for my previous case: server is recorded as failed, but without any …

fix healthchecker reload when some healthchecks are failed

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/main.c
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_parser.c

When keepalived was reloading a configuration, and VIPs were removed and accept mode was set on the VRRP instance, the removed VIPs were not deleted. This commit resolves the issue, and should resolve issue #382.
Logging startup and "already running" messages will help understand problems of keepalived running in a container - see issue #383.

Remove VIPs on reload if no longer in configuration

---

keepalived/vrrp/vrrp.c

VRRP IPv6 packets should be prioritised over user packets, just like for IPv4

Add internet network control support for IPv6

---

keepalived/check/ipvswrapper.c
keepalived/check/libipvs.c
keepalived/core/global_data.c
keepalived/include/ipvswrapper.h
keepalived/include/vrrp_if.h
keepalived/include/vrrp_iproute.h
keepalived/include/vrrp_netlink.h
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_iproute.c
keepalived/vrrp/vrrp_snmp.c
lib/parser.c
lib/signals.c

The majority of the commits are removing more pre Linux 2.6 code. There is also a commit that resolves the "unknown keyword" messages, and a cosmetic change to report the correct default for snmp socket.
The "unknown keyword" fix resolves issue #297.

More updates for removing pre-Linux 2.6 code, and stop "unknown keyword" messages.

---

keepalived/core/namespaces.c

The primary documentation for namespaces is a comment in the source code, so that comment should be as accurate as possible.

Fixed typo "leepalived" in comment

---

keepalived/include/vrrp_netlink.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_netlink.c

keepalived was only polling for netlink messages on the kernel reflection channel on a timed basis. If a large number of vmacs were added at startup, the netlink socket would run out of receive buffers, and an ENOBUFS error would occur when the netlink socket was read.
Polling for netlink messages after adding each interface resolves the problem.
This should resolve issue #392.

Stop "Netlink: Received message overrun (No buffer space available)" messages

---

keepalived/vrrp/vrrp.c

Issue #392 has identified a further instance where the kernel reflection netlink socket can experience a buffer overrun. In this case, with 200 vrrp interfaces each with a vmac, adding a notify_master script caused the overrun. This is caused by the overhead of executing open(), close() and fork() synchronously for each vrrp instance as it transitions to master.
I think we should consider having a queue for the notify scripts, so that the fork()s are executed asynchronously from the actual vrrp work. This queue should be a low priority queue, so that the vrrp actions (state transitions, adding interfaces/addresses etc) aren't delayed by initiating the notify scripts.

Add polling of netlink messages when entering master state

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/include/global_data.h
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_ipaddress.c
lib/Makefile.am
lib/Makefile.in
lib/timer.c
lib/timer.h

Both VRRP_TIMER_SKEW() and timer_cmp() could overflow for large timer values.
The addition of TIMER_NEVER is to support threads that don't want to time out.
The addition of default_interface keyword is to avoid having to add dev IFACE after each static route if they are not using eth0.

Fix calculation of skew time, and timer_cmp() for extreme cases, and minor changes

---

configure
configure.ac
doc/KEEPALIVED-MIB
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/check_daemon.c
keepalived/check/check_data.c
keepalived/check/check_parser.c
keepalived/check/check_snmp.c
keepalived/check/ipvswrapper.c
keepalived/check/libipvs.c
keepalived/core/global_parser.c
keepalived/core/main.c
keepalived/core/namespaces.c
keepalived/core/pidfile.c
keepalived/include/check_data.h
keepalived/include/ip_vs.h
keepalived/include/main.h
keepalived/include/pidfile.h
keepalived/include/vrrp_if.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_ndisc.c
keepalived/vrrp/vrrp_scheduler.c
keepalived/vrrp/vrrp_vmac.c
lib/config.h.in
lib/memory.c
lib/memory.h
lib/utils.c
lib/utils.h

Adding `instance red` to the config will add `_red` to the pid file names, e.g. `keepalived_red.pid`, thereby allowing multiple instances of keepalived to be run concurrently without the pid file names colliding.
`use_pid_dir` option puts the pid files in /var/run/keepalived rather than /var/run; the former is used already if keywords `instance` or `net_namespace` are used.

Add keywords instance and use_pid_dir, plus sundry fixes/improvements

---

keepalived/core/main.c
keepalived/core/namespaces.c
keepalived/vrrp/vrrp.c
test/netns-test.sh

Issue #389 requested an option for being able to test that a configuration file is valid.
This commit adds test/netns-test.sh script that will set up a network configuration in a separate namespace (default test) which mirrors the system's main configuration for interfaces that are specified in the keepalived config file. keepalived can then be run with the -s test (or whatever namespace has been used) to test the configuration completely independently from the main system.

Add script to setup a test environment in a separate namespace

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/Makefile.am
keepalived/check/check_api.c
keepalived/check/check_dns.c
keepalived/core/layer4.c
keepalived/include/check_dns.h
keepalived/include/layer4.h

Hi,
I implemented DNS helath checker.
It has been running stable for several years in our system.
I want merge it to the built-in health checker.
There is also a way to use MISC_CHECK, but we avoided it for the following reasons.
- MISC_CHECK requires /bin/sh
MISC_CHECK is using the system(3). It is equivalent to the "/bin/sh -c". Therefore, we can't use MISC_CHECK in environment does not have /bin/sh. It is, e.g. not uncommon in the application container environment.
- Risk of the process increase in MISC_CHECK
If misc_path of the program has blocked, the process will increase. You can check the symptoms with the following settings.
```
MISC_CHECK {
misc_path "/bin/sleep 3600"
misc_timeout 10 
}
```
It's results.
```
UID   PID  PPID  PGID   SID COMMAND
0 41010     1 41010 41010 …
```

Add DNS health checker

---

configure.ac
keepalived/check/check_parser.c
keepalived/check/ipvswrapper.c
keepalived/check/libipvs.c
keepalived/include/check_data.h
keepalived/include/ip_vs.h

Without this patch, pe selection doesn't work with kernel 3.10 on centos 7.

Add check for PE selection support

---

keepalived/vrrp/vrrp_ipset.c

Issue #435 identified that the wrong library name was being used when
attempting to open the ipset library.

Fix loading of ipset library when development library not installed

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_parser.c

Alexandre, @acassen 
This is an update of my previous pull request for making VRRPv2 not accept packets sent to the VIP/eVIPs unless the vrrp instance is the address owner. The default now, for the reason you pointed out that IPVS and other services running on the VIPs need accept mode as default, is that accept is the default unless strict mode is specified for an instance. Accordingly a `no_accept` keyword has been added to allow vrrp instances to behave in accordance with the RFCs.
I have changed the mode of operation for VRRPv3 so that it is now the same as VRRP2; in other words anyone who was using VRRPv3 and wanted packets addressed to the VIPs to be discarded will now have to add `no_accept` to their configuration.
If you're happy with the above approach, could you please merge it.

Add no_accept mode for VRRPv2 and standardise VRRPv3 with it

---

genhash/main.c
keepalived/check/check_daemon.c
keepalived/check/check_misc.c
keepalived/core/main.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_scheduler.c
lib/notify.c
lib/notify.h
lib/signals.c
lib/signals.h

Hi,
This is the proposal to the matter of mentioned in #429.
- Script process does not respond to SIGTERM (fe9638b)
```
Sep 26 16:31:03 lb01 Keepalived_healthcheckers[28302]: Process [28304] didn't respond to SIGTERM
Sep 26 16:31:03 lb01 Keepalived_healthcheckers[28302]: pid 28304 exited due to signal 9
Sep 26 16:31:06 lb01 Keepalived_healthcheckers[28302]: Process [28307] didn't respond to SIGTERM
Sep 26 16:31:06 lb01 Keepalived_healthcheckers[28302]: pid 28307 exited due to signal 9
Sep 26 16:31:09 lb01 Keepalived_healthcheckers[28302]: Process [28366] didn't respond to SIGTERM
Sep 26 16:31:09 lb01 Keepalived_healthcheckers[28302]: pid 28366 exited due to signal 9
```
I think there is a problem in the signal_handler_init().
In signal_handler_init(), it remember the original disposition …

[WIP] Fix process increase

---

keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_ipaddress.c

The address comparison was including ifa_index, but that wasn't being
set up until after clear_diff_vrrp() was called.

Fix clearing addresses no longer used after a reload

---

keepalived/include/vrrp_ipaddress.h
keepalived/include/vrrp_ipset.h
keepalived/include/vrrp_iptables.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_ipaddress.c
keepalived/vrrp/vrrp_ipset.c
keepalived/vrrp/vrrp_iptables.c

If an interface was specified for a VIP/eVIP, the iptables/ipset block
if not in accept mode for link local IPV6 addresses was specifying the
interface the vrrp instance was on rather than the interface the address
was added to.
This commit now makes the iptables/ipset entry specify the interface that
the address has been added to.

Use correct interface for iptables/ipset entries when not accept mode

---

configure
configure.ac

Indirect expansion (`${!foo}`) is a bashism, it's not POSIX-sh
compatible and is not supported by common shells except Bash and ZSH!
Configure script should be portable, hence strictly POSIX compliant.
Moreover it has shebang /bin/sh.

Fix illegal syntax in configure script

---

configure.ac
keepalived/check/check_daemon.c
keepalived/vrrp/vrrp_daemon.c

If the parent keepalived process is killed, the child processes will
be orphaned and can cause problem when attempting to restart
keepalived. This patch makes use of prctl with PR_SET_PDEATHSIG such
that all child processes will receive SIGTERM if the parent process
dies.
Signed-off-by: Ryan O'Hara <rohara@redhat.com>

Terminate child processes if parent dies

---

configure
configure.ac
keepalived/include/vrrp_ip_rule_route_parser.h
keepalived/include/vrrp_iproute.h
keepalived/vrrp/vrrp_ip_rule_route_parser.c
keepalived/vrrp/vrrp_iproute.c
keepalived/vrrp/vrrp_snmp.c
lib/config.h.in

RedHat have partially backported lightweight tunnel encapsulation
into their kernel, but not included MPLS or ILA. We need to have
conditional compilation for LWTUNNEL_ENCAP_MPLS and LWTUNNEL_ENCAP_ILA
rather than just checking for RTA_ENCAP.

Fix building on Centos 7/RHEL 7 re lightweight tunnel encapsulation

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5

Issue #484 identified that the documentation was not correct regarding
weights for tracking scripts.

Update documentation for tracking scripts weight 0

---

keepalived/check/ipwrapper.c

Several functions in check/ipwrapper.c were always returnung the same
value, and the code calling the functions then checked and returned an
error if the return value was not the value always returned. Also, for
some functions returning a value the return value was never checked in
the calling function.
Making the functions void, and removing the if (...) makes the code easier
to read, and potentially slightly more efficient.

ipwrapper.c: make functions void if return value not used or constant

---

doc/man/man5/keepalived.conf.5

Spent a good while trying to track down why my script wasn't executing (it was checking for 3 parameters and exiting if it didn't receive them).
The `notify_*` action documentation includes the $4 parameter (priority), but it was missing for the catch-all `notify` action.

Fix missing documentation for 4th parameter of notify action

---

configure
configure.ac
keepalived/check/check_data.c
keepalived/check/check_parser.c
keepalived/check/ipwrapper.c

When using the socket interface to configure IPVS (rather than the netlink interface), IPv6 isn't supported, so report the issue at configure time, and log an error if IPv6 IPVS configuration is requested at run time.
These commits also ensure that there isn't an attempt to mix IPv4 and IPv6 configuration within a single virtual server, since it isn't supported.

Improved handling  of IPVS with IPv6

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/include/global_data.h
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_print.c

If the situation had developed where two vrrp instances had become master (for example due to network isolation), it is possible that the ARP caches on some hosts may point to the lower priority master. This commit adds the option higher_prio_send_advert to force the lower priority master to send an advert when it transitions to backup. If lower_prio_garp_rep is set on the higher priority master, it will then send GARP messages, and the ARP caches on hosts should recover.

Add option to ensure GARPs are resent after recovering from 2 masters

---

keepalived/check/ipvswrapper.c
keepalived/core/main.c

These issues were found when testing pull request #571, since the way the container is set up it isn't possible to load the module from within a container.

Fix cleanup when cannot load ip_vs module

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/check_misc.c
keepalived/check/check_parser.c
keepalived/core/global_parser.c
keepalived/core/main.c
keepalived/include/main.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_print.c
lib/notify.c
lib/notify.h

The message about the default script user keepalived_script not existing was getting tedious.
The commit cause the warning to only be output if there is a script that would use keepalived_script.
There are various other script handling improvements.

Don't complaint if user keepalived_script doesn't exist it not needed

---

keepalived/vrrp/vrrp_data.c

There was no PARAMETER_UNSET value assigned to higher_prio_send_advert.
This caused the global value was not used for each VRRP instance.

Fix missing PARAMETER_UNSET for vrrp_higher_prio_send_advert

---

lib/logger.c

Thought this might be helpful for people not using/leveraging syslog facilities. Tracking events in daemontools logs (console logs) was problematic. Let me know if I can change anything or would prefer a different approach.

logger: output timestamps to console logs

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
doc/samples/sample_notify_fifo.sh
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/keepalived_netlink.c
keepalived/core/main.c
keepalived/include/global_data.h
keepalived/include/vrrp.h
keepalived/include/vrrp_ipaddress.h
keepalived/include/vrrp_notify.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_ipaddress.c
keepalived/vrrp/vrrp_notify.c
lib/notify.c
lib/notify.h
lib/parser.c
lib/scheduler.c
lib/scheduler.h

The notify FIFO is designed to resolve the problem of notify scripts potentially processing notify events in the wrong order, as identified in pull requests #568 and #587 and issue #584.

Add notify FIFO, and some minor changes

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
doc/samples/sample_notify_fifo.sh
keepalived/check/check_daemon.c
keepalived/check/check_data.c
keepalived/check/ipwrapper.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/keepalived_netlink.c
keepalived/core/main.c
keepalived/core/snmp.c
keepalived/include/global_data.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_notify.c
lib/notify.c
lib/notify.h
lib/scheduler.c
lib/scheduler.h

Issue #588 identified that keepalived could segfault if no router_id specified. Add a patch that should protect against this, although it appears that the problem would only occur if keepalived cannot get the hostname.
smtpServerPort wasn't being notified via SNMP
FIFO notify enhancements

Add FIFO notifies for LVS notification, and sundry fixes

---

keepalived/check/ipwrapper.c

Hi,
I found a code that seems to be a mistake in the process of clearing the IPVS service.
+ I think the first if statement of check the address family is mistake.
+ Unlike comments, it seems to be skipping only when the member number of vsg is 0.
I registered 3 entries in vsg and tested it.
```
Fri Jun  2 19:06:40 2017: Starting Keepalived v1.3.5 (06/02,2017), git commit v1.2.23-544-g7326bd8+
Fri Jun  2 19:06:40 2017: Opening file '/etc/keepalived/keepalived.conf'.
Fri Jun  2 19:06:40 2017: Starting Healthcheck child process, pid=38639
Fri Jun  2 19:06:40 2017: Opening file '/etc/keepalived/keepalived.conf'.
Fri Jun  2 19:06:40 2017: Initializing ipvs
Fri Jun  2 19:06:40 2017: Initing vs [sample]:0, vsg sample
Fri Jun  2 19:06:40 2017: Adding rs [192.168.2.1]:tcp:80
Fri Jun  2 19:06:40 …
```

Fix incorrect expression in clear_services()

---

keepalived/check/check_daemon.c

Hi,
I fixed the problem that "Bad file descriptor" error occurs at reloading.
This problem occurs when there is no virtual_server (or no real_server in the virtual_server) in the config when reloading.
*Original code*
```
Wed Jun  7 18:42:45 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun  7 18:42:45 2017: Got SIGHUP, reloading checker configuration
Wed Jun  7 18:42:45 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Jun  7 18:42:45 2017: Virtual server [sample]:0 has no real servers - ignoring
Wed Jun  7 18:42:45 2017: Removing Virtual Server Group [sample]
Wed Jun  7 18:42:45 2017: IPVS (cmd 1160, errno 9): Bad file descriptor
Wed Jun  7 18:42:45 2017: IPVS (cmd 1156, errno 9): Bad file descriptor
```
*This pull request code*
```
Wed Jun  7 19:08:14 2017: Opening …
```

Fix bad file descriptor error at reload with no virtual servers

---

keepalived/check/ipwrapper.c

Hi,
I fixed a problem that some server removed from the new configuration will not be deleted at reload.
(I think that this pull request solves issue of #492)
+ current state
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
-> RemoteAddress:Port     Forward Weight ActiveConn InActConn
TCP  192.168.100.1:http lc
-> 192.168.2.2            Masq    0      0          0         
-> 192.168.2.3            Masq    1      0          0     
```
Inhibit_on_failure is set in 192.168.2.2
+ delete realserver `192.168.2.2` from virtualserver & reload
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
-> RemoteAddress:Port     Forward Weight ActiveConn InActConn
TCP  192.168.100.1:http lc
-> 192.168.2.2            Masq    0      0 …
```

Delete disabled inhibit servers at reload

---

keepalived/check/check_data.c

Hi,
I have fixed an issue where forwarding_method was not set for sorry_server.
When `lb_kind` is DR:
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
-> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.100.1:http lc
-> 192.168.2.2:http             Route   0      0          0         
-> 192.168.2.254:http           Masq    1      0          0   
```
sorry_server(192.168.2.254)'s Forward should be `Route`, but  it was set `Masq`.
This problem seems to be occurring at the https://github.com/acassen/keepalived/commit/b54589ae32406c2ea9f7bc523b27c66570c0d082.
For sorry_server, copying forwarding_method from virtual_server solved the problem.
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler …
```

Set sorry_server's fowarding_method

---

lib/scheduler.c

If a thread times out, then it will move to the ready list and either
READ_TIMEOUT or WRITE_TIMEOUT.  If we then cancel this thread, it doesn't
get cleaned up and gets stuck back on the unused list for reuse.

Fix thread_cancel() for timed out threads

---

configure.ac
genhash/Makefile.am

Notably, downgrade autoconf dependency to the one used on Cent OS6, and fix genhash link phase by moving libraries to link to in appropriate place.

Various build fixes.

---

keepalived/vrrp/vrrp_if_config.c

```
$ make
... (snip) ...
CC       vrrp_if_config.o
vrrp_if_config.c: In function ‘clear_rp_filter’:
vrrp_if_config.c:536:3: warning: implicit declaration of function ‘log_message’ [-Wimplicit-function-declaration]
log_message(LOG_INFO, "Unable to read sysctl net.ipv4.conf.all.rp_filter");
^
vrrp_if_config.c:544:2: error: ‘all_rp_filter’ undeclared (first use in this function)
all_rp_filter = rp_filter;
^
vrrp_if_config.c:544:2: note: each undeclared identifier is reported only once for each function it appears in
vrrp_if_config.c:551:3: error: ‘default_rp_filter’ undeclared (first use in this function)
default_rp_filter = rp_filter;
^
vrrp_if_config.c: In function ‘restore_rp_filter’:
vrrp_if_config.c:585:6: error: ‘all_rp_filter’ undeclared (first use in this function)
if (all_rp_filter …
```

Fix build error at when _HAVE_IPV4_DEVCONF_ was undefined

---

keepalived/check/check_api.c
keepalived/check/check_daemon.c
keepalived/check/check_dns.c
keepalived/check/check_http.c
keepalived/check/check_misc.c
keepalived/check/check_smtp.c
keepalived/check/check_tcp.c
keepalived/check/ipwrapper.c
keepalived/include/check_api.h

This patch is a proposal to #608.
As pointed out by issue, there is a problem that inconsistency will occur in the checker_id before and after reload.
Between the old_rs and the new_rs, it is necessary to correctly migrate the checker_id stored in failed_checkers.
However, comparing the definitions of the checkers and confirming the identity takes time and effort. So, as a provisional implementation, if realserver is not alived I tried to handled all checkers as failed.
After this, I trying to implement the comparison of all health checkers.

[WIP] Migrate failed checkers at reload

---

keepalived/core/main.c

The correct name of the parameter is "--config-id" instead "--config_id".

Fix typo in help

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/include/global_data.h
keepalived/vrrp/vrrp_dbus.c

If you want to run multiple keepalived processes on the same machine and enable the DBus interface on all of them, only one will obtain the service name on the bus.
I've added a new `dbus_service_name` option to specify a custom name (other daemons like e.g. `dnsmasq` follow the same approach).
While going through the DBus code I also noticed a few issues with regards to error handling. Not all glib DBus calls are checked for errors, and if errors occur, the error is not free'ed. This has also been fixed.

Allow custom DBus service name

---

lib/parser.c

Hi,
Commit 3455c4a9 changed `read_conf_file()`'s behaviour to exit when `glob()` returned non-success. Calling `exit(3)` from within a utility function like `read_conf_file` causes a number of issues:
- Keepalived will refuse to start when used together with `include` to modularize configuration (e.g. `include /etc/keepalived/puppet.d/*.conf` which may be empty).
- It also causes the main process to exit uncleanly during reloads, leaving orphan child processes around. This issue is serious, as it leaves keepalived in a crippled state; subsequent attempts to restart    the keepalived service without manually killing the VRRP/healthcheck children first will fail.
The original commit message makes it clear that this is about the main configuration file, which is essential indeed. However, …

parser: do not exit when glob() doesn't match any files

---

keepalived/check/check_data.c

If the first real server ip address doesn't match the address
family of the virtual server, then we need to skip parsing the
rest of the real_server block.

Fix segfault when parsing invalid real server

---

configure
configure.ac
keepalived/check/check_parser.c
keepalived/core/main.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_parser.c
lib/parser.c
lib/parser.h

Issue #768 complained about restrictions of placing of { and } in config file; those restrictions are now removed.
These commits also streamline some configuration parsing and fix one or two minor bug fixes.

Allow flexibility of positioning or { and } in config files

---

keepalived/include/vrrp_arp.h
keepalived/vrrp/vrrp.c

Linux kernel version 4.15 changed the libc/kernel headers suppression
logic in a way that introduces collisions:
In file included from ./../include/vrrp_ipaddress.h:32:0,
from ./../include/vrrp_arp.h:31,
from vrrp.c:29:
/home/peko/autobuild/instance-1/output/host/arc-buildroot-linux-uclibc/sysroot/usr/include/linux/in.h:29:3: error: redeclaration of enumerator 'IPPROTO_IP'
IPPROTO_IP = 0,  /* Dummy protocol for TCP  */
^
/home/peko/autobuild/instance-1/output/host/arc-buildroot-linux-uclibc/sysroot/usr/include/netinet/in.h:33:5: note: previous definition of 'IPPROTO_IP' was here
IPPROTO_IP = 0,    /* Dummy protocol for TCP.  */
^~~~~~~~~~
Include the libc netinet/in.h header first to suppress the kernel
header.
In addition, add _GNU_SOURCE to vrrp.c for the libc provided in6_pktinfo …

Fix build with Linux kernel headers v4.15

---

keepalived/include/vrrp_if_config.h
keepalived/vrrp/vrrp_if_config.c
keepalived/vrrp/vrrp_vmac.c

An issue was identified where keepalived was reporting permission
denied when attempting to add an IPv6 address to a VMAC interface.
It turned out that this was because
/proc/sys/net/ipv6/conf/default/disable_ipv6
was set to 1, causing IPv6 to be disables on all interfaces that
keepalived created.
This commit clears disable_ipv6 on any VMAC interfaces that
keepalived creates if the vrrp instance is using IPv6.

Clear /proc/sys/net/ipv6/conf/IF/disable_ipv6 when create VMACs

---

keepalived/check/check_parser.c

The logic test from inet_aton() appears to be inverted.
Tested-by: Simon Kirby <sim@hostway.ca>
Fixes: fecfe5af9913 ("Improve persistence handling")

Fix persistence_granularity IPv4 netmask validation

---

doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
genhash/include/main.h
genhash/main.c
genhash/ssl.c
keepalived/check/check_http.c
keepalived/check/check_ssl.c
keepalived/include/check_http.h

This adds a `enable_sni` parameter to SSL_GET, making sure the check
passes the virtualhost in the SNI extension during SSL handshake.
It also adds support for SNI to genhash.
fixes #804

add support for SNI in SSL_GET check

---

keepalived/core/keepalived_netlink.c

Even though the checker process doesn't subscribe to RTNLGRP_LINK
messages, it appears that older kernels (certainly 2.6.32) can
send RTM_NEWLINK (but not RTM_DELLINK) messages. This occurs
when the link is set to up state.
Only the VRRP process is interested in link messages, and so the
checker process doesn't do the necessary initialisation to be able
to handle RTM_NEWLINK messages.
This commit makes the checker process simply discard RTM_NEWLINK
and RTM_DELLINK messages, rather than assuming that if it receives
an RTM_NEWLINK message it must be the VRRP process.
This problem was reported in issue #848 since the checker process
was segfaulting when a new interface was added when the -a command
line option was specified.

Make checker process handle RTM_NEWLINK messages with -a option

---

configure
configure.ac

net-snmp-config output can include compiler and linker flags that
refer to spec files that were used to build net-snmp but may not
exist on the system building keepalived. That would cause the build
done by configure to test for net-snmp support to fail; in particular
on a Fedora 28 system that doesn't have the redhat-rpm-config package
installed.
This commit checks that any spec files in the compiler and linker
flags returned by net-snmp-config exist on the system building
keepalived, and if not it removes the reference(s) to the spec file(s).
See https://bugzilla.redhat.com/show_bug.cgi?id=1544527 for further
details.

Fix building on Fedora 28

---

lib/signals.c

If incorrect signals are being received we don't want to flood the
logs with messages, so only report an invalid signal number if the
signal is outside the range of signals already received.
Also, this is essentially debug code, so wrap it in conditional
compilation so that it can be enabled when needed.

Make the signal value checking code only report each signal once

---

keepalived/vrrp/vrrp_scheduler.c

Hello,
TSM logs are always sent to stdout. This generates a lot of noise if keepalived is run in foreground.
This change sends TSM log using log_message, only if LOG_DETAIL_BIT is set.
Gautier

Don't send TSM logs to stdout, but log_message

---

keepalived/core/keepalived_netlink.c
keepalived/vrrp/vrrp_vmac.c

Since commit 18ec95add483 ("Make vmac_xmit_base work for IPv6
instances") VRRP advertisements are sent from the base interface and not
from the vmac interface when vmac_xmit_base is set.
Therefore, there is no need to configure a link-local address on the
vmac interface. This also means that we don't need to regenerate a
link-local address for the vmac if the link-local address was removed
from the base interface, or inherit a link-local address in case one was
configured on the base interface.
Signed-off-by: Ido Schimmel <idosch@mellanox.com>

Don't create a link-local address for vmac when vmac_xmit_base is set

---

keepalived/core/keepalived_netlink.c
keepalived/vrrp/vrrp_if_config.c
keepalived/vrrp/vrrp_vmac.c

Fix setting arp_ignore and arp_filter on bridge interfaces, and creating VMACs on 2.6.32 and earlier kernels 

---

keepalived/vrrp/vrrp_print.c

At some point, newlines have disappeared from the /tmp/keepalived.stats file generated on SIGUSR2, which made it completele unreadable for machines and hard to read for humans, so I've added the newlines back.
This is what it was like for me in 2.0.5.
````
VRRP Instance: Bar  Advertisements:    Received: 0    Sent: 18120  Became master: 1  Released master: 0  Packet Errors:    Length: 0    TTL: 0    Invalid Type: 0    Advertisement Interval: 0    Address List: 0  Authentication Errors:    Invalid Type: 0    Type Mismatch: 0    Failure: 0  Priority Zero:    Received: 0    Sent: 0VRRP Instance: Foo  Advertisements:    Received: 0    Sent: 18120  Became master: 1  Released master: 0  Packet Errors:    Length: 0    TTL: 0    Invalid Type: 0    Advertisement Interval: 0    Address List: 0 …
```

Add newlines to the keepalived.stats output for better readability.

---

doc/KEEPALIVED-MIB.txt
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/include/vrrp.h
keepalived/include/vrrp_notify.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_json.c
keepalived/vrrp/vrrp_notify.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_snmp.c

If a lower priority router has transitioned to master, there has presumably
been an intermittent communications break between the master and backup. It
appears that servers in an Amazon AWS environment can experience this.
The problem then occurs if a notify_master script is executed on the backup
that has just transitioned to master and the script executes something like
a `aws ec2 assign-private-ip-addresses` command, thereby removing the address
from the 'proper' master. Executing notify_master_rx_lower_pri notification
allows the 'proper' master to recover the secondary addresses.
This problem was reported in issue #950.

Add notify_master_rx_lower_pri script option and FIFO output

---

doc/KEEPALIVED-MIB.txt
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/check/check_data.c
keepalived/check/check_parser.c
keepalived/check/check_snmp.c
keepalived/include/check_data.h

This is similar to the sh scheduler. Options are the same but we
duplicate everything. An alternative would have been to reuse the
names for the sh scheduler.
The mh scheduler is supported starting from Linux 4.18. It's a
consistent hash scheduler.

Add mh scheduler for LVS

---

keepalived.spec.in

I tried to build RPM package for keepalived v2.0.7, but I got this error.
```
$ rpmbuild -ba keepalived.spec
error: line 31: Unknown tag: @WITH_REGEX@BuildRequires: pcre2-devel
```
I think `@WITH_REGEX@` in `keepalived.spec.in` is mistake. 
This should be `@WITH_REGEX_TRUE@`, shouldn't it?
I modified, then it works.

Fix variable name in keepalived.spec.in file

---

configure.ac
doc/keepalived.conf.SYNOPSIS
doc/man/man5/keepalived.conf.5
keepalived/bfd/bfd_daemon.c
keepalived/check/check_daemon.c
keepalived/core/Makefile.am
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/keepalived_netlink.c
keepalived/core/main.c
keepalived/core/track_process.c
keepalived/include/global_data.h
keepalived/include/track_process.h
keepalived/include/vrrp.h
keepalived/include/vrrp_data.h
keepalived/include/vrrp_track.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_ipaddress.c
keepalived/vrrp/vrrp_iproute.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_track.c

The track_process feature acts like having a track_script calling pidof/pgrep/pkill/killall, but is more efficient, more responsive and add extra features.

Add track_process for vrrp instances

---

keepalived/vrrp/vrrp_if.c

Otherwise, if keepalived has virtual_routes configured, we create
a virtual interface and bring it up and down, current code will bring
VRRP state to FAULT and never return.
```
```

Also skip route not configured with down interface

---

lib/parser.c

```
(unsigned long)timer * TIMER_HZ;
```
A long type var timer is cast to `unsigned long`, it's scale falls.
For example var timer is `0.7`.
By the C Lang rules, Cast priority is higher than calculation, so var timer become `0` and multiply TIMER_HZ.

Remove variable timer of unsigned long cast in read_timer().

---

keepalived.spec.in

When uninstalling keepalived, it occurs two problems.
```
sudo yum remove keepalived / sudo rpm -e keepalived
```
- it raises following syntax error.
```
>> line 7: syntax error near unexpected token `fi'
```
- resolved: e5e9a79
- After uninstall keepalived, the process continue to run.
- resolved: 641b861

In uninstalling keepalived which installed by rpm package with upstart system, it occurs problems.

---

keepalived/check/check_misc.c
keepalived/include/check_data.h

False means not equal and true means equal.

Fix reutrn value of notify_script_compare misusing issue.

---

keepalived/core/global_parser.c

NFT_TABLE_MAXNAMELEN has been added only in kernel 4.1 with
https://github.com/torvalds/linux/commit/1cae565e8b746f484f1ff1b71d2a1c89d7cf0668
So define it to 32 if it is not defined
Fixes:
- http://autobuild.buildroot.org/results/a33433abeb122cfb15f7f21ab777e84040bdcb8b
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

global_parser.c: fix build with kernel < 4.1

---

doc/KEEPALIVED-MIB.txt
doc/man/man5/keepalived.conf.5
keepalived/check/check_daemon.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/snmp.c
keepalived/include/global_data.h

Currently all known virtual servers and their real servers are removed one at a
time at shutdown. With large configurations on a busy system, this can take some
time.
Add an option just like the existing 'lvs_flush' which operates on shutdown.
Typical environments with a single keepalived instance can take advantage of
this option to achieve a faster shutdown or restart cycle.
Signed-off-by: Patrick Talbert <ptalbert@redhat.com>

Add option to flush lvs on shutdown

---

keepalived/check/check_api.c
keepalived/check/check_daemon.c
keepalived/check/ipwrapper.c
keepalived/include/ipwrapper.h

This commit enhances pull request #1180 by ensuring that new alpha mode checkers for an existing real server don't cause the real server to be brought down at reload until the checkers have run.

Make new real servers at reload start down if have alpha mode checkers

---

configure.ac

This fixes FTBFS on Ubuntu 14.04:
make[2]: Entering directory `/home/thresh/keepalived/keepalived'
gcc -DHAVE_CONFIG_H -I. -I../lib    -I./include -I ../lib  -g -D_GNU_SOURCE -Wall -Wextra -Wunused -Wstrict-prototypes -Wbad-function-cast -Wcast-qual -Wdisabled-optimization -Wfloat-equal -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wtrampolines -Wundef -Wuninitialized -Wunsuffixed-float-constants -Wunused-macros -Wvariadic-macros -fPIE -Wformat -Werror=format-security …

Propagate libm to KA_LIBS

---

keepalived/check/check_parser.c

Hi, All.
In the current keepalived version, keepalived.conf does not allow the zero-weight real server.
This patch enables it.
I think that it is effective in the following situations.
1. when restart to keepalived, zero-weight real server connection is maintained
If we will set to zero-weight real server by ipvsadm, we will set to the zero-weight real server keepalived.conf, and restart to keepalived, we will keep the zero-weight real server.
Thereby, the active and in-active connections allocated to real server can be maintained.
2. zero-weight real server can be done from the keepalived starting
When I want to add zero-weight real server, I should set to one-weight real server at keepalived.conf, and I set manually the real server weight to zero by ipvsadm.
In this situation, there is …

keepalived.conf may set to zero to the real server's weight

---

keepalived/check/ipvswrapper.c

Correct me if I'm wrong, now we can handler single and group together, so it seems no need to add a  redundant judgement.

 Delete redundant code

---

keepalived/vrrp/vrrp.c

compilation error occurs on the kernel with MAC VLAN support and IFLA_LINK_NETNSID not support.
```
vrrp.c: In function 'vrrp_complete_instance':
vrrp.c:2756:5: error: expected ')' before '{' token
{
^
vrrp.c:2772:4: error: expected expression before '}' token
}
^
```
This PR corrects the above error.

correct syntax error when _HAVE_VRRP_VMAC_ && no HAVE_IFLA_LINK_NETNSID

---

keepalived/vrrp/vrrp_notify.c

Issue #1267 identified that the parameters for a notify script were missing when it was a shell script with no #! shebang.

Ensure 4 extra parameters are set for notify scripts with no shebang

---

keepalived/check/check_http.c
keepalived/include/check_http.h

The origin status_code only support one specific code, now we can
support http status_code of the same class. That's to say, we can
use 1xx to represent 100-199, 2xx means 200-299 ans so on.
eg: The configure as follows:
url {
path /index.html
status_code 2xx 3xx
}
which means we consider all status_code range in [200,399] is ok.
Of course the following configure is either 200 or [300,399] is ok.
url {
path /index.html
status_code 200 3xx
}

support http status_code group

---

keepalived/core/global_parser.c
keepalived/core/smtp.c
keepalived/include/layer4.h
keepalived/include/smtp.h
keepalived/include/vrrp_data.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_static_track.c

Issue #1275 identified that SMTP alerts were not working. The SMTP alerts
were broken by commit 5860cf3 - "Make checker fail if ENETUNREACH returned
by connect()", since the SMTP state machine was not updated to handle the
addition value in enum connect_result.
This commit adds code to handle the additional enum, but also makes the
code less sensitive to such changes, and more likely to produce compiler
warnings/errors if appropriate updates are not done in the future.

Fix sending SMTP alerts

---

keepalived/check/check_http.c

Although even if min > max, the code works well. We better to print
the error config to let the user know this.

add min max judge

---

keepalived/vrrp/vrrp_json.c

Changes, according to https://github.com/acassen/keepalived/issues/1293

Fix for "last_transition" in JSON (issue #1293)

---

keepalived/core/track_process.c

Issue #1291 identified a segfault when keepalived was monitoring the bgpd process and frr was stopped and restarted (causing bgpd to stop and restart). The pull request resolves the segfault.

Fix process tracking when threads change their COMM value

---

lib/json_writer.c

Changes, according to https://github.com/acassen/keepalived/issues/1299.

Fix for JSON characters escaping (issue #1299)

---

keepalived/check/ipwrapper.c

When we do not config vsg, during reloading,
the old and new vsg is NULL, so we can not
use old(new)->vsg->addr_range or
old(new)->vsg->vfwmark directly.
Signed-off-by: Jie Liu <liujie165@huawei.com>

Fix segfault when we do not config vsg

---

keepalived/vrrp/vrrp.c

This incorporates the patch in pull request 1310, and also fixes the code.

Fix checking for VMAC/IPVLAN no longer used after reload

---

doc/man/man5/keepalived.conf.5
keepalived/check/check_http.c
keepalived/check/check_ssl.c
keepalived/include/check_http.h

Pull request #1306 identified that second and subsequent URLs in an HTTP_GET checker were not being executed after the first check. Unfortunately the patch provided didn't handle retry_it quite properly.
A number of enhancements were possible to enable faster startup and recovery, and also to ensure that all URLs are checked continuously.

Various fixes/performance improvements for HTTP_GET checker

---

keepalived/check/check_http.c

Under normal circumstances, status_code returns 100-599,
but if it is a constructed abnormal reply message,
it may be out of the range, resulting in the status_code
array out of bounds, and then keepalived segfault.
Signed-off-by: Jie Liu <liujie165@huawei.com>

Fix overflow status code

---

keepalived/check/check_dns.c

Sometimes, users set two type values by mistake in keepalived.conf,
and the first is right and the second one is not in DNS_TYPE[].
Then the dns_check->type is set successfully when parsing first type value
, which may be different from the default SOA. As for the second one,
the dns_type_handler func will print error info "Defaulting to SOA",
actually, currently the dns_check->type may be not equal to SOA.
Here, we will print the dns_type_name(dns_check->type) instead of "SOA".
Signed-off-by: Zhiqiang Liu <liuzhiqiang26@huawei.com>

DNS_CHECK: correct error info in dns_type_handler func

---

keepalived/vrrp/vrrp_arp.c
keepalived/vrrp/vrrp_ndisc.c

Some times , send the gratuitous ARP message should set sll_protocol , let some drivers can evaluate which protocol we use

sll_protocol should be set to  0x806

---

configure.ac
doc/KEEPALIVED-MIB.txt
doc/man/man5/keepalived.conf.5
keepalived/bfd/bfd_parser.c
keepalived/core/keepalived_netlink.c
keepalived/core/main.c
keepalived/include/vrrp.h
keepalived/include/vrrp_if.h
keepalived/include/vrrp_track.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_parser.c
keepalived/vrrp/vrrp_scheduler.c
keepalived/vrrp/vrrp_snmp.c
keepalived/vrrp/vrrp_static_track.c
keepalived/vrrp/vrrp_track.c

If "reverse" is specified after "weight" for a vrrp tracker, the priority will be decreased when the tracker is up, and increased when the tracker is down (i.e. in the opposite direction from normal.

Add VRRP tracking reverse option, and SNMP updates

---

doc/man/man5/keepalived.conf.5
keepalived/check/ipwrapper.c

Virtual server persistence and scheduler configuration, and real server forwarding methods can be updated without removing and recreating the virtual or real server, so don't use them when comparing old and new virtual/real servers, and update the relevant parameters if they are changed on reload.

Do not use VS persistence and scheduler type or RS forwarding when comparing at reload

---

keepalived/core/main.c

**Issue**
In some circumstances, it takes a few seconds from the start of keepalived to call signal_init function. When a user tries to reload configuration in that time window, keepalived is killed.
**Solution**
This patch introduces a new function signals_ignore, which is called right after keepalived_main call.

Ignore reloading signals till signal_init call

---

keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_iproute.c

Issue #1390, after the original issue identified was resolved, added an additional issue relating to virtual routes not being added if they were configured using a new VIP. Although changing VIPs in a vrrp_instance on a reload seems dubious (backup instances will reject the adverts since the advertised addresses don't match), it has been possible to change the code to handle the issue.

Allow new virtual routes to use new VIPs on reload

---

keepalived/check/check_parser.c

'mh-fallback' and 'mh-port' cannot be used in the configuration file

fix: unknown keyword 'mh-fallback' and 'mh-port'

---

keepalived/check/check_misc.c

github @lankstra pointed out that the check for kill failing for
misc check scripts was inverted, so this commit corrects that, and
the code now matches the similar code in vrrp_script_child_thread().

Fix detecting of kill failure for MISC_CHECK scripts

---

TODO
configure.ac
doc/man/man5/keepalived.conf.5
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/keepalived_netlink.c
keepalived/core/main.c
keepalived/include/global_data.h
keepalived/include/vrrp_ipset.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_firewall.c
keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_ipaddress.c
keepalived/vrrp/vrrp_ipset.c
keepalived/vrrp/vrrp_iptables.c
keepalived/vrrp/vrrp_nftables.c
lib/memory.h

Use either iptables or nftables but not both
Use nftables instead of iptables configuration if the iptables command is iptables-nft
Automatically use nftables if iptables and nftables are not configured and no_accept or vmacs are configured
Various tidying up of the nftables/iptables code

Updates for iptables/nftables use.

---

keepalived/core/main.c
lib/signals.c

Issue #1561 identified that if a child process segfaulted while it was
terminating, the segfault was not reported by the parent process, making
the termination look as though nothig had failed.
This commit now ensures that if a child process does not exit cleanly then
the parent process will report it.

Improve handling by parent process of children terminating

---

doc/man/man5/keepalived.conf.5
keepalived/check/ipvswrapper.c
keepalived/check/libipvs.c
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/core/namespaces.c
keepalived/include/global_data.h
keepalived/include/namespaces.h

- this patch adds `net_namespace_ipvs` parameter
- when set, ipvs socket is created in the targeted namespace
it allows to properly split traffic between healthchecks and ipvs
without having to use any complex setup with veth/bridge/iptables:
- do the healthcheck traffic in the root namespace
- receive the VIP traffic in a given namespace
the patch had the necessary plumbing for two cases:
- without libnl, we use a generic `socket_netns` function to create given
socket - if no namespace has been specified, the effect is the same as
before, we only create a socket. If a namespace was previously
specified, we first switch to the namespace, then create the socket,
and move back to the root namespace
this function could be used in the future in any other extension while
opening a socket.
- …

ipvs: allow to locate ipvs rules in a namespace

---

genhash/Makefile.am
keepalived/Makefile.am
keepalived/bfd/Makefile.am
keepalived/check/Makefile.am
keepalived/core/Makefile.am
keepalived/trackers/Makefile.am
keepalived/vrrp/Makefile.am

NetSNMP will add Perl headers to the search path in CPPFLAGS. It
contains `parser.h` which will conflict with Keepalived's one. Just
move the search path for other directories before the remaining
CPPFLAGS to fix this.

build: fix out-of-tree builds when SNMP is enabled

---

doc/source/configuration_synopsis.rst

The keyword `smtp_connect_timeout` in table is wrongly `smtp_connection_timeout`, so fix it.

Fix Document bug: Update configuration_synopsis.rst

---

keepalived/check/check_ping.c
keepalived/check/check_tcp.c

Signed-off-by: wangxp006 <wangxiaopeng7@huawei.com>

To facilitate log analysis，all checker timeout logs use the same format

---

lib/scheduler.c

fix issue#1631
keepalived running too long，which lead to print “scheduler：epoll_wait error ：invalid argument”

bugfix epoll_count is reversed

---

keepalived/check/check_parser.c
keepalived/core/global_parser.c
keepalived/include/global_data.h

although it's type is unsigned ,timeout is must <=UINT_MAX / HZ.  ip_vs_add_service function in ipvs module  check it by u->timeout > (UINT_MAX / HZ).  LVS_MAX_TIMEOUT value is 
appropriate. at the same time ipvsadm use 31 days always.

fix-persistence_timeout-range

---

doc/man/man5/keepalived.conf.5

At least with dns_check on 2.0.20, delay_before_retry defaults to the value of delay_loop.

Say what delay_before_retry default value is

---

doc/man/man5/keepalived.conf.5

At least, I experienced this behavior with dns_check in version 2.0.20 and "smtp_alert true".

[doc] Improve doc of checker_log_all_failures

---

keepalived/check/check_dns.c

**When using dns_checker, if the type and name are not configured, the default type SOA and the default name ‘.’ will be used. When the default value is used, it cannot go online.
```
dns_check->type = DNS_DEFAULT_TYPE;
dns_check->name = DNS_DEFAULT_NAME;
```
The configuration file is as follows:**
```
virtual_server 22.22.4.149 53 {
delay_loop 6
lb_algo rr
lb_kind DR
protocol UDP
alpha
hysteresis 0
quorum 1
quorum_up "/usr/sbin/ip addr add 22.22.4.149 dev lo"
real_server 22.22.38.68 53 {
weight 2
DNS_CHECK {
connect_port 53
connect_timeout 1
retry 1
bindto 22.22.24.104
}
}
}
```
[root@openEuler keepalived]# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
-> RemoteAddress:Port           Forward Weight ActiveConn InActConn
UDP  22.22.4.149:53 …

dns_checker cannot go online correctly when using the default dns name '.'

---

keepalived/check/check_udp.c

close fd to avoid leak when udp checker failed

fix failure of udp checker caused leakage of fd

---

keepalived/check/check_misc.c

With keepalived 2.0.20 a failed misc_check with retry=2 is logged as following:
```
Jul  1 15:51:33 nodename Keepalived_healthcheckers[30447]: Misc check for [[10.7.2.223]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 2 retries (exited with status 9).
Jul  1 15:51:43 nodename Keepalived_healthcheckers[30447]: Misc check for [[10.7.2.223]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 2 retries (exited with status 9).
Jul  1 15:51:53 nodename Keepalived_healthcheckers[30447]: Misc check for [[10.7.2.223]:tcp:53 VS [10.7.2.26]:tcp:53] by [/usr/bin/dig] failed after 2 retries (exited with status 9).
Jul  1 15:51:53 nodename Keepalived_healthcheckers[30447]: Removing service [10.7.2.223]:tcp:53 to VS [10.7.2.26]:tcp:53
```
So there always is printed "failed after …

Fix misc_check log of failed retry check

---

keepalived/check/check_misc.c

I saw there was a bug in line
https://github.com/acassen/keepalived/blob/141c341feefd6391e955ecf825b321d90d396f61/keepalived/check/check_misc.c#L439
because if `global_data->checker_log_all_failures` is true, `checker->log_all_failures` is still _false_, so there was again the effect that with checker_log_all_failures globally set, there was on every recheck logged "failed after x retries" (see #1676). This is fixed with this patch.
This also handles the case of 1 retry correctly, so there would not be logged "failed after 1 retries" anymore.
This makes also the logging identically in both cases of `checker_log_all_failures` being set or unset. The only difference is, that with `checker_log_all_failures` set, the checks before the last will be logged. But the last check (or the only check …

Fix misc_check logging

---

doc/man/man5/keepalived.conf.5

Since I have two keepalived clusters (old one and new one) in the same LAN in parallel,
I wanted to be sure that they do not intefere with VRRP messages. Since authentication is deprecated and should no be used,
I did not want to only rely on the virtual router ID, but also use a separate multicast address for the second cluster.
So I set vrrp_mcast_group4 to 224.0.**10**.18 without researching multicast address assigning (and here in the doc was nothing said about which address one could set).
But with 224.0.**10**.18 there came the message "Receive advertisement timeout" and both nodes had the virtual IP addresses (split brain).
So, VRRP simply did not work.
Then I researched and saw that the network where the default address 224.0.0.18 is in, is 224.0.0.0/24.
So I changed …

[doc]  Typically don't change default MCast address

---

keepalived/check/check_http.c

When exceeding  the check failed threshold ,  HTTP logs is inconsistent with other checkers logs. modify the logs to make them consistent with other logs。
This  is helpful when parsing logs with scripts
Aug  3 15:03:32 openEuler Keepalived_healthcheckers[87646]: UDP_CHECK on service [22.22.52.199]:udp:53 failed after 1 **retries**.
Aug  3 15:04:00 openEuler Keepalived_healthcheckers[87646]: HTTP_CHECK on service [22.22.52.199]:tcp:443 failed after 3 **retry.**
Aug  3 15:06:12 openEuler Keepalived_healthcheckers[87646]: DNS_CHECK ([22.22.8.53]:udp:53) read timeout from socket after 1 **retries**
Aug  3 15:06:12 openEuler Keepalived_healthcheckers[87646]: TCP_CHECK on service [22.22.8.53]:tcp:5001 failed after 1 **retries**

 Modify HTTP retry logs to make them consistent with other checkers

---

doc/man/man5/keepalived.conf.5

Config docs seem to indicate the value is both ms and seconds

Removing conflicting vrrp param documentaion

---

doc/man/man5/keepalived.conf.5

It's -o, not -O in ipvsadm, see
https://kernel.googlesource.com/pub/scm/utils/kernel/ipvsadm/ipvsadm/+/b18edce035ad01cd1828573275cbf221a3ac02c6/ipvsadm.8

Fix documentation of "ops" parameter

---

doc/man/man5/keepalived.conf.5
keepalived/core/global_parser.c
lib/parser.c
lib/parser.h

while using `reload_check_config`, it is useful to make sure to fail
when the config file or its includes are not possible to be open.
it will avoid a situation where a reload continues to happen while an
important config included cannot be open.

parser: report_config_error when failing opening a file

---

keepalived/trackers/track_file.c

Without including inttypes.h, compilation of 2.2 fails with such errors:
```
track_file.c:450:32: error: expected ')' before 'PRIi64'
```
Here was my build config:
```
Keepalived configuration
------------------------
Keepalived version       : 2.2.0
Compiler                 : gcc gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Preprocessor flags       : -D_GNU_SOURCE -I/usr/include/libnl3
Compiler flags           : -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wall -Wextra -Wunused -Wstrict-prototypes -Wabsolute-value -Waddress-of-packed-member -Walloca -Walloc-zero -Warray-bounds=2 -Wattribute-alias -Wbad-function-cast -Wcast-align …
```

trackers: fix building with gcc

---

.travis.yml

More and more deployment and development is being done on ARM64/AARCH64 architecture.
It would be good if Keepalived is being tested on ARM64!

Add a job to build and test on ARM64 CPU architecture

---

INSTALL

* fixes a typo in `less` command
* adds missing dash before Docker' run `it` argument
* use HTTPS for Git clone operation
* spell SELinux as at https://selinuxproject.org/page/Main_Page

Small improvements to the README

---

keepalived/include/check_data.h

ipvs: Fix compiling when magic library not available

---

doc/man/man5/keepalived.conf.5.in

Clarify preempt_delay in keepalived.conf(5) to mean that preempt_delay
can't be used to speed up taking over as master.
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>

doc: clarify preempt_delay in keepalived.conf(5)

---

keepalived/bfd/bfd_scheduler.c
keepalived/vrrp/vrrp_firewall.c
lib/scheduler.c

Hi,
This PR will fix three minor instances of "time-of-check vs time-of-use"-problems.
The problems are found with a tool detecting when pointers are checked against NULL after they have been dereferenced.
There are three instances found in this project:
---
Problem: Superfluous/pointless check @ line 946 - if 'ai_in == NULL' it was already dereferenced on line 943. 
Suggestion: A change from the current form (see comment on line 946):
```C
941    if ((ret = getaddrinfo(NULL, BFD_CONTROL_PORT, &hints, &ai_in)))
942        log_message(LOG_ERR, "getaddrinfo() error %d (%s)", ret, gai_strerror(ret));
943    else if ((data->fd_in = socket(AF_INET6, ai_in->ai_socktype, ai_in->ai_protocol)) == -1) {
944        if (errno == EAFNOSUPPORT) {
945            /* IPv6 is disabled on the system, so we …
```

Fix time-of-check time-of-use 'bugs'

---

keepalived/vrrp/vrrp_vmac.c

Fix for the issue #2026.
On VRRPv3 IPv6 with use_vmac mode, after disabling vmac-xmit-base, the
following error happens:
> Oct 29 11:33:10 ubuntu Keepalived_vrrp[1663]: (vrrp): send advert error 22 (Invalid argument)
No VRRP packets are emitted anymore.
Tested against the procedure of the #2015 issue. No regression on it.
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>

vrrp: fix disabling vmac-xmit-base with VRRPv3 IPv6 use_vmac

---

keepalived/dbus/org.keepalived.Vrrp1.conf

The DBus policy did not restrict the message destination, allowing any
user to inspect and manipulate any property.
Signed-off-by: Vincent Bernat <vincent@bernat.ch>

dbus: fix policy to not be overly broad

---

keepalived/bfd/bfd_daemon.c
keepalived/check/check_bfd.c
keepalived/check/check_daemon.c
keepalived/core/main.c
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_scheduler.c
lib/notify.c
lib/process.c
lib/process.h

1. Handle unexpected close of BFD pipes
2. Thread debugging - deregister parent thread addresses earlier
3. Ensure PDEATHSIG does not become disabled
4. Add 'static' which was missing from a couple of variables.

Various fixes

---

doc/source/installing_keepalived.rst

Adding `--location` in curl command example.
(There's a 301 redirect at the given URL.)
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

doc: quick fix in installation doc

---

configure.ac
keepalived/check/check_ssl.c

`SSL_set0_rbio` is provided by libressl since version 3.4.0 and https://github.com/libressl-portable/openbsd/commit/c99939f9665a9c3c648682b4987df46600b70efc but `SSL_set0_wbio` is not provided resulting in the following build failure:
```
/nvmedata/autobuild/instance-9/output-1/host/lib/gcc/s390x-buildroot-linux-gnu/10.3.0/../../../../s390x-buildroot-linux-gnu/bin/ld: check/libcheck.a(check_ssl.o): in function `ssl_connect':
check_ssl.c:(.text+0x7da): undefined reference to `SSL_set0_wbio'
```
Fixes:
- http://autobuild.buildroot.org/results/76f72a3c7350ea265e2277c89d68e5256410e94c
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix build with libressl

---

snap-tools/keepalived-wrapper
snap/snapcraft.yaml

Launchpad no longer has 3.10 kernel packages, the oldest is 3.13.

snap: Use kernel 3.13 instead of 3.10 for old kernels

---

keepalived/vrrp/vrrp_data.c

Trackers etc have lists for vrrp instances that are tracking them.
Therefore the trackers, and their references, must be freed before the
vrrp instances are freed.

vrrp: deley freeing vrrp instances until all references are freed

---

doc/man/man5/keepalived.conf.5.in
keepalived/include/vrrp.h
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_parser.c

This keyword suppresses	warnings for no virtual ipaddresses configured
and allows none	to be configured when using VRRPv3.

vrrp: Add no_virtual_ipaddress keyword

---

keepalived/check/check_http.c
keepalived/check/check_parser.c
lib/parser.c
lib/parser.h

Commits 8a3f145 - "fix mem leaks when virtualhost and snmp_name
are duplicate" and 86bbb2e - "fix mem leaks when virtualhost is
duplicate" changed the behaviour of virtualhost and snmp_name
configuration if there were duplicate definitions to use the
first defined entry, whereas previously the last defined entry
was used, albeit with a memory leak.
This commit retains the memory leak fixes, but reverts the
behaviour to use the last definition rather than the first.

check: use last entry if duplicate definition

---

doc/man/man5/keepalived.conf.5.in

It wasn't clear that enable_script_security stops defaulting to
running scripts as the user under which keepalived is running
(usually root), but defaults to keepalived_script in the absence
of any script user being specified.

doc: Update description of enable_script_security

---

configure.ac

For example fwmarks are enabled by default, and so --disable-fwmark would be specified rather than --enable-fwmark, so the warning needs to be about the use of --disable-fwmark if LVS is disabled, rather then warn about --enable-fwmark.

configure: give warnings re enable/disable options the right way around

---

doc/source/installing_keepalived.rst

build-essentials does not exist but build-essential does.

doc: fix build-essential package install

---

doc/man/man5/keepalived.conf.5.in
keepalived/core/global_data.c
keepalived/core/global_parser.c
keepalived/include/global_data.h
keepalived/include/global_json.h
keepalived/vrrp/vrrp_json.c

The original JSON format did not allow for adding additional object types other than the original vrrp instances. This commit adds a json_version 2, which puts the vrrp instances in a named array and adds an array of the track_processes.

vrrp: Add optional new JSON format including track_process details

---

doc/man/man5/keepalived.conf.5.in
keepalived/core/global_parser.c

keepalived.conf(5) man page incorrectly specified that the default umask was IWGRP | IWOTH, whereas it is IXUSR | IRWXG | IRWXO.

core: Add IRWXU etc for umask and update documentation

---

keepalived/vrrp/vrrp.c

Fixes: a534e94 vrrp: Use vrrp_t flags for checking if unicast is in use Resolves issue #2270

vrrp: Fix checking for unicast if no interface specified

---

keepalived/dbus/org.keepalived.Vrrp1.Instance.xml

The type of the `Name` property of `org.keepalived.Vrrp1.Interface` seems to be incorrect.
In the code (https://github.com/acassen/keepalived/blob/333e086155507eb7ee30378cc9ff88d48af2d338/keepalived/vrrp/vrrp_dbus.c#L843), the property is a `(s)`, however, the XML interface file states that the type is `s`.
It causes problems when using the interface.

dbus: fix type of Name property in Interface

---

keepalived/vrrp/vrrp_vmac.c

Do not replace the IPv6 Link-Local address by the same address.

vrrp: do not replace the ipv6 link-local by the same address

---

keepalived/check/check_ping.c
keepalived/include/check_ping.h
lib/scheduler.c
lib/scheduler.h

By keeping the sockets used for pings open, the ICMP id field now remains the same for each echo request.
The sequence number is now per ping check, and is now sent in big endian order.

ipvs: ping check - use consistent ICMP id and fix sequence number

---

keepalived/core/keepalived_netlink.c

solve #2294 
if VRRP_VMAC is not enabled, VRRP_VMAC_BIT AND VRRP_VMAC_XMITBASE_BIT are invalid. However, VRRP_VMAC_BIT AND VRRP_VMAC_XMITBASE_BIT are used without checking _HAVE_VRRP_VMAC_ in netlink_if_address_filter().
fixes: 74b203b ("vrrp:restore the vmac ipv6 link_local after flapping")

vrrp: fix compilation error when VRRP_VMAC is disabled

---

keepalived.spec.in

Both Fedora and openSUSE now recommends to use SPDX shortname format for License.

spec: Migrate to SPDX license

---

keepalived/include/vrrp_if_config.h
keepalived/vrrp/vrrp_if_config.c
keepalived/vrrp/vrrp_vmac.c

Setting arp_ignore to 1 ensures that the VMAC interface does not respond to ARP requests for IPv4 addresses not configured on the VMAC.

vrrp: Set sysctl arp_ignore to 1 on IPv6 VMACs

---

keepalived/check/check_misc.c
keepalived/check/ipvswrapper.c

issue: when using virtual server groups, if all rs down and sorry server up, at this time remove/add vs entry in configure file and then do reload, vs entry can not be removed.
fix: add/remove sorry server same as normal rs when reload server groups

ipvs: add/remove sorry server of group server when reload

---

doc/man/man5/keepalived.conf.5.in

fix: Fix typo (replace `it` by if`) in manpage

Update keepalived.conf.5.in (fix typo)

---

keepalived/vrrp/vrrp_vmac.c

It is useful in many instances to set up firewall rules based on interface groups so that sets of interfaces may be aggregated by group and matched with a single rule rather than by listing them all.
Prior to this change, when use_vmac or use_ipvlan is used, new interfaces are created with the default group, which breaks this ability.
Further complicating the issue is that nftables resolves interface names to ifindex at load time. This is problematic with keepalived's interface creation, which usually comes after the firewall loading, forcing the use of iifname, oifname instead (similar to iptables -i, -o).
By copying the group value, such firewall rules can continue to work regardless of the use_vmac or use_ipvlan settings, since packets may now arrive on, or be routed out from, the new …

vrrp: For use_vmac and use_ipvlan, copy the group from the base interface

---

keepalived/core/main.c

check_start_stop_script_secure() checks that the parent process has not changed while it is doing its checks, so we need to set the pid of the parent process (main_pid) before calling the function.
There is a further complication that called getppid() too soon after a fork() with the parent process exiting after the fork means that we don't get the pid of the new parent, so we need to loop until getppid() returns a diffweent pid.

core: make startup/shutdown scripts work when not using --dont-fork

---

keepalived/vrrp/vrrp_parser.c
lib/rttables.c
lib/rttables.h

lack macro HAVE_DECL_FRA_SUPPRESS_IFGROUP,
which is similar with get_rttables_group().
This fix build error when macro HAVE_DECL_FRA_SUPPRESS_IFGROUP=0  (on centos 7  kernel 3.10.0)
```
rttables.c:328:31: error: use of undeclared identifier 'rt_groups'
328 |         return find_entry(name, id, &rt_groups, RT_GROUPS_FILE, NULL, INT32_MAX);
|                                      ^
rttables.c:328:42: error: use of undeclared identifier 'RT_GROUPS_FILE'
328 |         return find_entry(name, id, &rt_groups, RT_GROUPS_FILE, NULL, INT32_MAX);
```

Fix lack macro for find_rttables_group()

---

configure.ac
keepalived/vrrp/vrrp.c
keepalived/vrrp/vrrp_if.c
lib/parser.c

GCC 13 now reports an error when "false" is used instead of "NULL". This commit now resolves the three instances of the wrong use identified.

vrrp: correct some parameter/return types

---

lib/notify.c

GCC 13 identified a bug in clean_path where the source of a strcpy() was always NULL.

all: fix clean_path()

---

keepalived/core/main.c
lib/notify.c

Due to the path field not being set to NULL, it was attempting to exec a random string when reload_check_config was configured.

core: initialise script structure in start_validate_reload_conf_child()

---

doc/man/man5/keepalived.conf.5.in
keepalived/check/libipvs.c

This resolves commit 930f3b72 "ipvs: Don't duplicate storage of 32 bit SNMP stats"

ipvs: Fix stats handling when only have 32 bit stats

---

keepalived/vrrp/vrrp_daemon.c

I am the [maintainer](https://github.com/openwrt/packages/blob/master/net/keepalived/Makefile#L22) of the keepalived packages in OpenWrt.
There is also a [LuCI](https://github.com/openwrt/luci/tree/master/applications/luci-app-keepalived) frontend that queries the status of keepalived.
To get the status of keepalived, the json signal handling is used.
The problem now is, that when the LuCI status page is  open in the browser, this removed message in the PR is show every 3 second on status query. In my opinion, this floods the log and is not necessary.

vrrp: remove logging on status output

---

configure.ac

Commit 42a746c - "configure: ${prefix} defaults to NONE which messes up DEFAULT_CONFIG_FILE" broke the checking of whether a secondary default config file location is required. This commit resolves the issue.

configure: fix secondary config file location when using --prefix=/usr

---

keepalived/check/check_misc.c

The exit code of a misc checker can be read via SNMP. The misc check code was not updating the last exit code if the checker was not dynamic, the checker was already down (i.e. returned a non 0 exit code), and the exit code changed from the previous exit code. This meant that the exit code reported via SNMP was not the latest exit code, but the exit code that caused the status of the checker to change.
This commit now updates the last exit code, even if the checker is already down.

ipvs: Update status code of misc checker if changes while in fault state

---

keepalived/core/track_process.c

Github user Bbulatov identified that terminate_delay was being used when fork_delay should have been used. While investigating, it was also found, albeit in a debug message that fork_delay was used where terminate_delay should have been used. Further, the process state was being updated immediately even if the fork_delay was being invoked.

vrrp: fix track process reinitialize fork delay timer

---

doc/man/man8/keepalived.8.in
keepalived/bfd/bfd_daemon.c
keepalived/check/check_daemon.c
keepalived/core/main.c
keepalived/include/main.h
keepalived/vrrp/vrrp_daemon.c

This is needed for running keepalived under GDB (see https://bugzilla.kernel.org/show_bug.cgi?id=9039#c8).

all: add --ignore-sigint option

---

keepalived/bfd/bfd_daemon.c
keepalived/check/check_daemon.c
keepalived/core/main.c
keepalived/core/pidfile.c
keepalived/include/main.h
keepalived/include/pidfile.h
keepalived/vrrp/vrrp_daemon.c

There was a window when keepalived starts up when if two (or more) instances were starting at the same time, they might not detect the other instance is running.
This commit add advisort file locking on the PID files to ensure that only one instance can run at a time.

core: ensure only one instance of keepalived can run per config_id

---

keepalived/vrrp/vrrp_iptables.c
keepalived/vrrp/vrrp_nftables.c

MLDv2 listener reports were being handled, but not MLDv1. This commit now adds handling of MLDv1 listener reports as well.

vrrp: Duplicate/drop MLDv1 listener reports on VMACs

---

keepalived/vrrp/vrrp_if.c
keepalived/vrrp/vrrp_iproute.c

If an interface is deleted, it is identified by the ifindex being set to 0, so we must ignore any interfaces with a 0 ifindex.

vrrp: check ifindex != 0 before using the interface

---

keepalived/core/main.c
keepalived/core/pidfile.c
keepalived/include/main.h
keepalived/include/pidfile.h

If a child process is respawned, the old pidfile may or may not still exist. If it doesn't exist, we need to recreate it. If it still exists we need to reset our file offset and truncate the file before re-wrighting it.

all: Ensure pid file exists when respawning child process

---

keepalived/bfd/bfd_data.c

This fixes an incompatible pointer type [-Wincompatible-pointer-types] issue when compiling keepalived with GCC 14 [1] in 32-bit architectures where time_t size is 64 bits.
[1] https://gcc.gnu.org/gcc-14/porting_to.html
The issue was found when compiling keepalived in Ubuntu  24.10 for armhf with gcc 14  (https://launchpadlibrarian.net/749244069/buildlog_ubuntu-oracular-armhf.keepalived_1%3A2.3.1-1_BUILDING.txt.gz)

bfd: use time_t to avoid implicit ptr type casting

---

keepalived/bfd/bfd_daemon.c
keepalived/bfd/bfd_data.c
keepalived/check/check_daemon.c
keepalived/check/check_data.c
keepalived/core/global_data.c
keepalived/core/main.c
keepalived/include/bfd_data.h
keepalived/include/check_data.h
keepalived/include/global_data.h
keepalived/include/vrrp_data.h
keepalived/vrrp/vrrp_daemon.c
keepalived/vrrp/vrrp_data.c
keepalived/vrrp/vrrp_dbus.c

Although none of the warnings was due to any error in the code that could cause a problem. for some of the warnings reported is was quite straightforward to modify the code in a way that was just as readable and would avoid the warnings.
Two of the warnings reported could not possibly result in an error, and checks (return code or null dereferences) were not made since the design of the code was such that they could not occur.

Fix some warnings identified by a static analyzer

---

configure.ac
keepalived/vrrp/vrrp_daemon.c
lib/rttables.c
lib/rttables.h

A request to add an entry to /usr/share/iproute2/rt_addrprotos.d for keepalived to use for an address protocol was rejected with the following reason:
iproute2 now allows apps to drop custom files in
/etc/iproute2/rt_addrprotos.d, so this can be managed within keepalived.
(see https://lore.kernel.org/netdev/ca8a1945-3a02-4830-b39d-5e90c0515c91@kernel.org/T/#t)
So this commit now adds an entry to
/etc/iproute2/rt_addrprotos.d/keepalived.conf if the version of iproute2 >= 6.12, or to /etc/iproute2/rt_addrprotos if the version is between 6.3 and 6.11.

vrrp: always add a keepalived entry to rt_addrprotos is none exists

---

Dockerfile.in

Avoids this error when building on Alpine in Docker:
```
9.540 configure: error: Missing/unusable kernel header file <linux/types.h> - is kernel headers package installed?
```
Of course, this still requires you comment out `#include <linux/if_ether.h>` first.

Install linux-headers pkg to build in Docker

---

keepalived/vrrp/vrrp_data.c

If a vrrp instance has no interface configured (so it is unicast), processing SIGUSR1 resulted in a segfault.

vrrp: fix segfault when instance has no interface configured

---

configure.ac
keepalived/vrrp/vrrp.c

Fix segfault if unicast_src_ip is not configured on interface, and allow bind() to work when address in not configured on interface.

Updates re unicast_src_ip

---

lib/parser.c

**Description:**
This pull request resolves a bug in the HEX_STR parsing logic for the UDP_CHECK feature. Previously, HEX_STR values ending with 0xff were incorrectly flagged as errors. This impacted configurations that used HEX_STR in UDP_CHECK payload and require_reply fields, potentially leading to configuration failures or misbehavior.
**Issue Example:**
The following configuration file, which demonstrates a UDP_CHECK with a payload containing 0xFFFF, failed to load in earlier versions due to a parsing error:
```
! Configuration File for keepalived
! This example demonstrates UDP_CHECK, a component of LVS configuration.
global_defs {
notification_email {
acassen
}
notification_email_from Alexandre.Cassen@firewall.loc
smtp_server 192.168.200.1
smtp_connect_timeout 30
router_id …
```

parser: Fix error handling for HEX_STR parsing in UDP_CHECK

---

goodies/check_conditional_tests
snap-tools/keepalived-wrapper

some non-critical refactors of BASH/SH scripts
* snap-tools: use sh as interpreter; misc tweaks
* use sh as interpreter since we already have sh compatibility,
* sh-compat: only change export to be on 2 lines,
* set SNAP if somehow unset
* quote MAGIC and exec call
* goodies: use bash mapfile and array to store found C files

refactor misc shell script tweaks

---

keepalived/vrrp/vrrp_if.c

When an interface is (re-)added, setup_interface() should be called even if vrrp->flags is set (eg VRRP_FLAG_NOPREEMPT).
Tests to avoid setup_interface() before commit a0ce04a checked vrrp->vmac_flags, but the change mistakenly mixed the test with other vrrp flags.
The bug manifests in cases where the only vrrp_instance on an interface uses a feature that sets a vrrp->flags bit (eg nopreempt), and then the interface is deleted and re-added (eg nmcli con down <intf>, nmcli con up <intf>).  The vrrp->flags value causes setup_interface() to not be called, and the vrrp interface never times-out to reach master state.
If other vrrp_instance's exist for the same interface, then the bug doesn't manifest (the other instance calls setup_interface, and the (eg nopreempt) instance will transition to …

vrrp: interface add should call setup_interface()

---

keepalived/vrrp/vrrp_if.c

Commit 1383336 - "vrrp: interface add should call setup_interface()" identified that the change in commit a0ce04a from if (vrrp->vmac_flags) to if (vrrp->flags) was incorrect, and specific bits needed to be checked.
This commit resolves another instance of the same error.

vrrp: check specific flags in vrrp-flags

---

snap/snapcraft.yaml

Add missing rules for the riscv64 architecture.
This patch is enough to build the keepalived snap locally for riscv64.

snap: enable riscv64 building

---

doc/man/man5/keepalived.conf.5.in

Commit 9c7d00c adds a log to replace keyword `thread_timer_expired` with `timer_expired_backup`, but didn't update keepalived.conf.5
Also updated the doc to refer to "thread timer expired" as that what appears to be actually logged in scheduler.c

doc: use timer_expired_backup in place of thread_timer_expired

---

keepalived/core/pidfile.c

Patch to add O_CLOEXEC flag when opening pidfiles.
Commit 2c4cd3b introduced the use of pid files for instance locking, which keeps the pidfile descriptors open.  However, the O_CLOEXEC flag was missing so the open descriptors are passed to all exec'd processes (scripts etc).
I noticed this when adding SELinux permissions for keepalived to use ping as a vrrp_script, and saw the following denial:
```
type=AVC msg=audit(1738090198.716:585): avc:  denied  { write } for  pid=21305 comm="ping" 
path="/run/vrrp.pid" dev="tmpfs" ino=3178 scontext=system_u:system_r:ping_t:s0 
tcontext=system_u:object_r:keepalived_var_run_t:s0 tclass=file permissive=0
```
I created a test script to dump the open file descriptors, and found one extra descriptor for /run/vrrp.pid
Ideally, the code that exec's any …

core: add O_CLOEXEC flag to pidfiles

---

snap/snapcraft.yaml

Following a suggestion at
https://answers.launchpad.net/launchpad/+question/820140
to get builds working for riscv64, the commit comments out the architectures keyword to see if that will make it build for riscv64.

snap: Remove architectures keyword from snapcraft.yaml

---

snap/snapcraft.yaml

This reverts commit ff8e84f526e54ab84117dccf6ae759a6397f5c1c.
Removing the architectures keyword did not resolve the problem.

Revert "snap: Remove architectures keyword from snapcraft.yaml"

---

lib/scheduler.c

In a situation when a child was timed out, but not yet processed, the thread is THREAD_CHILD_TIMEOUT type and remains on ready queue. If it gets terminated in this state, it needs to be removed from rb tree child_pid and transitioned to THREAD_CHILD_TERMINATED, but without additional moving it to ready queue as it is already there.
The erase from child_pid tree is required to clean up pid from not terminated childs tree, but it needs to be done exactly once as rb tree implementation is not guarded against double removal. Erasing or adding same element multiple times, leads to malformed red-black tree and segmentation faults.
This patch removes double erase in described scenario.
Might fix #2548

Fix segfault caused double erase from child_pid rb tree

---

snap/snapcraft.yaml

Though libraries are staged the daemon fails to search them in the snap path.
Closes #2561

snap: set LD_LIBRARY_PATH for daemon

---

doc/source/installing_keepalived.rst

There is a typo in the installation documentation: instead of pcre2-**r**evel, it should be pcre2-**d**evel.
Thank you for your project.

There is a typo in the installation documentation: pcre2-revel

---

keepalived/vrrp/vrrp_scheduler.c

This is a fix for a bug introduced during refactoring thread functions in: https://github.com/acassen/keepalived/pull/1626
When a vrrp script is to be run (initially or after specified interval), first it is checked if it's in IDLE state. If not a log message is printed informing about skipping run due to script being either running or timed out. However despite not being idle the code continues to run new script process.
In heavily loaded systems this caused running multiple instances of vrrp script at the same time.
This patch brings back missing return, which was lost during refactoring.

Skip running not idle vrrp scripts

---

doc/man/man5/keepalived.conf.5.in
keepalived/vrrp/vrrp.c

There was no need to limit the up debounce timer in the same way that the down debounce timer has to be limited, so this commit removes the 2 * advert interval upper limit.

vrrp: allow interface up debounce timer to exceed 2 * advert interval

---

keepalived/vrrp/vrrp_daemon.c

During the vrrp_startup_delay time, if keepalived is reloaded with no more startup_delay, the startup_delay is never timed out and all received adverts is discarded.
The commit causes the startup_delay timer to be reinstated after a reload with no more startup_delay if the timer has not yet expired.
Fixes: 58483b22c8 ("vrrp: Handle a reload before vrrp_delayed_start has expired")

vrrp: handle a reload with no more startup_delay

---

snap/snapcraft.yaml

The previous patch set the LD_LIBRARY_PATH environment variable, but the path was set as /usr/lib/amd64 rather than /usr/lib/x86_64.

snap: yet another attempt to get LD_LIBRARY_PATH correct

---

snap-tools/keepalived-wrapper
snap/snapcraft.yaml

LD_LIBRARY_PATH is now being correctly set, but the binary executables don't seem to be using it.

snap: try and get snap executable to see LD_LIBRARY_PATH

---

snap-tools/keepalived-wrapper

Although LD_LIBRARY_PATH is now set in the environment, it is not being exported to keepalived-wrapper.

snap: Construct and set LD_LIBRARY_PATH

---

snap-tools/keepalived-wrapper

/bin/sh on Ubuntu is a link to dash, which doesn't support [[ ... ]].

snap: Fix keepalived-wrapper changes

---

keepalived/trackers/track_file.c

If a track_file was configured, but the configured file did not exist, then the track_file structure was freed, but the path to the (non existent) file was not freed.

track_file: fix memory leak

---

keepalived/vrrp/vrrp_iptables.c

Github issue #2627 reported that there was a potential null pointer dereference in handle_iptable_rule_to_vip() due to global_data->vrrp_iptables_inchain being checked to be not null, but subsequently used without such a check.
Since handle_iptable_rule_to_vip() is only called if the pointer is non NULL, the check for non NULL is removed, and a comment added at the beginning of the function to state that it is always non NULL.

vrrp: remove redundant not NULL check
