keepalived/Makefile.in
* Also,  changed perms for keepalived.sysconfig from 755 to 644.
=> * Fixed filenames and paths so that _make uninstall_ properly removes initscript and man pages.

doc/man/man5/keepalived.conf.5, keepalived/check/check_smtp.c, keepalived/include/check_smtp.h, lib/logger.c, lib/logger.h, lib/parser.c, lib/parser.h
This fixes the bugs with SMTP checker that were reported by Chris Adams.
=> smtp_check bugfixes

keepalived.spec.in
This way, this doesn't need to be updated at each version.
=> spec: use @VERSION@ to put appropriate version

keepalived.spec.in
Reverts acassen/keepalived#176
=> Revert "Update keepalived.spec.in"

doc/keepalived.conf.SYNOPSIS, keepalived/core/global_parser.c, lib/utils.c, lib/utils.h
Added support for domain name in config `smtp_server`, such as `smtp_server mail.example.com`
=> make 'smtp_server' config to support domain name

doc/man/man5/keepalived.conf.5, doc/samples/keepalived.conf.vrrp.routes
Hello,
I spent some time to find the info.
So a short patch to add it into man and sample.
=> Add info to set a default gateway into man and sample.

configure
This is the first of a series of pull requests. While making some changes to improve the IPv6 functionality, I came across a number of improvements that could be made. I have attempted to group the commits into functional areas as far as is possible, and have made the changes on separate branches, so they will be the subject of separate pull requests.
The patches will almost certainly fail to apply if the pull requests are not processed in the original order.
=> Update configure in line with configure.in - request #1

configure, keepalived/check/check_data.c, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_ipaddress.c, lib/list.c, lib/list.h
There are a number of potential memory leaks that these commits resolve.
=> Memory leaks - request #2

configure, configure.in, doc/keepalived.conf.SYNOPSIS, doc/man/man5/keepalived.conf.5, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/include/global_data.h, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_ipaddress.c
Reverts acassen/keepalived#224
=> Revert "iptables - request #3"

doc/keepalived.conf.SYNOPSIS, doc/man/man5/keepalived.conf.5, keepalived/check/check_daemon.c, keepalived/vrrp/vrrp_daemon.c
=> Don't reset and then set again signal disposition during reload of vrrp

keepalived/vrrp/vrrp_scheduler.c
=> Don't enter backup state if receive 2 SIGHUPs in close succession

doc/keepalived.conf.SYNOPSIS, keepalived/check/check_data.c, keepalived/check/check_parser.c
This commit resolves issue #127.
=> Add reporting ops mode, and minor tidying up of virtual_server config

keepalived/check/check_http.c, keepalived/include/vrrp_iproute.h, keepalived/include/vrrp_iprule.h, keepalived/libipvs-2.4/Makefile.in, keepalived/libipvs-2.4/libipvs.c, keepalived/libipvs-2.6/Makefile.in, keepalived/libipvs-2.6/libipvs.c, keepalived/vrrp/Makefile.in, keepalived/vrrp/vrrp_iproute.c, keepalived/vrrp/vrrp_iprule.c, keepalived/vrrp/vrrp_iptables_calls.c, lib/Makefile.in, lib/memory.c, lib/memory.h, lib/parser.c, lib/rttables.c, lib/rttables.h
This commit updates pull request #153 to work in a consistent manner to other keepalived functionality.
Also resolve some malloc()/free() issues.
=> Add support for iprule and iproute table names. Also resolve some malloc/free issues.

keepalived/vrrp/vrrp_ipaddress.c
=> Fix parsing of scope for ip addresses

keepalived/check/check_data.c, keepalived/check/check_http.c
Free HTTP_REQ buffers and ssl-related data on reload
=> Fix memory leaks on reload

keepalived/vrrp/vrrp.c
Currently the sync state is rebuilt from the member states after
config reload. This changes now reloads the previous sync state
after reload, and then pushes this back to the group members. If a
new group member is added during the reload, then the new group
will accept the sync group state. If a group member is removed
during a reload, then a special case will be executed to force
the sync-group state to BACKUP. This is required so that an
alternative backup peer for the removed group is given an
opportunity to take over the gateway.
Fixes issue #285
=> Restore sync-state after reload

keepalived/core/main.c, lib/parser.c, lib/parser.h
=> Report and exit if configuration file(s) not found/readable

configure, configure.ac, keepalived/vrrp/vrrp_iptables_calls.c
=> Fix building with Linux < 3.4 when ipset development libraries installed

keepalived/include/vrrp.h, keepalived/include/vrrp_if.h, keepalived/vrrp/Makefile.in, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_if.c, keepalived/vrrp/vrrp_netlink.c, keepalived/vrrp/vrrp_parser.c, keepalived/vrrp/vrrp_scheduler.c, keepalived/vrrp/vrrp_snmp.c, keepalived/vrrp/vrrp_vmac.c
=> Fix compiling without macvlan support

keepalived/include/vrrp.h, keepalived/include/vrrp_scheduler.h, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_scheduler.c
Make function name less confusing.
=> read_to() -> read_timeout()

configure, configure.ac, keepalived/include/vrrp_print.h, keepalived/vrrp/vrrp_iptables.c, keepalived/vrrp/vrrp_iptables_calls.c, keepalived/vrrp/vrrp_print.c
Also makes most functions in vrrp_print.c static.
=> Enable building on Linux 4.5.x

keepalived/vrrp/vrrp.c
This should resolve issues #310 and #313.
=> Fix segmentation fault when no VIPs configured

keepalived/core/main.c, lib/parser.c
=> Improve checking of existance and readability of config files

keepalived/check/check_snmp.c
This commit should resolve issue #350.
=> Enable compilation with development net-snmp headers

keepalived/vrrp/vrrp.c, lib/utils.c
=> Resolve multi-master problem after keepalived instances isolated from each other

doc/keepalived.conf.SYNOPSIS, doc/man/man5/keepalived.conf.5, keepalived/check/check_http.c
=> Re-enable a real server using HTTP_GET or SSL_GET after failure

keepalived/include/vrrp_iproute.h, keepalived/include/vrrp_iprule.h, keepalived/vrrp/vrrp_daemon.c, keepalived/vrrp/vrrp_iproute.c, keepalived/vrrp/vrrp_iprule.c
=> Fix adding new static ip addresses after reload

configure, configure.ac, keepalived/include/global_data.h, keepalived/include/vrrp_iptables.h, keepalived/include/vrrp_iptables_calls.h, keepalived/vrrp/vrrp_ipaddress.c, keepalived/vrrp/vrrp_iptables.c, keepalived/vrrp/vrrp_iptables_calls.c, lib/config.h.in, lib/utils.c, lib/utils.h
Commit a40aeb8 resolves a problem identified in issue #406.
=> Fix iptables entries for accept mode, other iptables fixes, and make write_stacktrace a configure option

doc/keepalived.conf.SYNOPSIS, doc/man/man5/keepalived.conf.5, keepalived/check/check_data.c, keepalived/check/check_parser.c, keepalived/check/check_snmp.c, keepalived/check/ipvswrapper.c, keepalived/include/check_data.h, lib/vector.h
Support passing libipvs flags by configuration file.
keyword for flags is lb_flags
for example:
lb_flags flag-1 flag-2 hashed
=> Adding libipvs flags support

keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_vmac.c
Issue #449 identified a problem with re-using VMACs after a reload. This then led to further issues being identified, and the commits here resolve those issues as well.
=> Resolve finding, and reusing VMAC interfaces on reload, and deletion of ones no longer used

doc/KEEPALIVED-MIB.txt, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_print.c, keepalived/vrrp/vrrp_snmp.c
=> Further changes for script init state failed (commit 1e93da0)

keepalived/check/ipwrapper.c
Fix Sorry Server handling on start/reload
* Do not remove it if already in place, and same server required
* add the sorry server on start in alpha mode (quorum down at start)
* add the new sorry server on a down VS on reload (quorum down at reload)
See issue #490
=> sorry_server load/reload on failure

doc/man/man5/keepalived.conf.5
This commit updates commit 075f0e6
=> Update man page for notify script parameters

configure, configure.ac, keepalived/core/main.c, lib/Makefile.am, lib/Makefile.in, lib/config.h.in
Use date/year of latest git commit for copyright and date output with -v option.
=> Make builds repeatable, and copyright date reflect latest commit

configure, configure.ac, keepalived/core/main.c, keepalived/vrrp/vrrp_iptables_calls.c, lib/config.h.in
Also fix updating of core dump pattern
=> Fix creation of iptables entries on more recent kernels

lib/scheduler.c
=> Fix high performance child finder cleanup code

keepalived/include/vrrp_ipaddress.h, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_daemon.c, keepalived/vrrp/vrrp_ipaddress.c
=> Fix removing left-over addresses if keepalived aborts

keepalived/check/ipwrapper.c, keepalived/core/main.c, lib/Makefile.am, lib/Makefile.in, lib/assert.c
Minor improvements are send assert messages to syslog, and improve getopt_long() handling
=> Enable sorry server at startup if needed, and minor improvements

.travis.yml
This is to initiate a first build by Travis-CI.
=> Add additional entry to Travis-CI build matrix

configure, configure.ac, keepalived/check/check_api.c, keepalived/check/check_daemon.c, keepalived/core/main.c, keepalived/vrrp/vrrp_daemon.c, lib/assert.c, lib/config.h.in, lib/scheduler.c, lib/signals.c
Start making --enable_debug configure option work again
Generalise handling of signals
Don't assume json header files are in /usr/include/json-c
Improve a log message
Fix building with musl libc
=> Various minor changes

keepalived/vrrp/vrrp.c
Issue #771 reported a segfault which this commit now resolves.
=> Fix sync groups with only one member

lib/signals.c
Fix for signals not working on CentOS 6.9.
=> Fix SIG_MAX - issue 864

snap/snapcraft.yaml
=> Update snapcraft.yaml for 1.4.x+git

keepalived/core/keepalived_netlink.c
=> Fix building with --enable-debug configure option

doc/keepalived.conf.SYNOPSIS, doc/man/man5/keepalived.conf.5, doc/man/man8/keepalived.8, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/core/main.c, keepalived/core/pidfile.c, keepalived/core/smtp.c, keepalived/include/global_data.h, keepalived/include/main.h, keepalived/vrrp/vrrp_dbus.c, keepalived/vrrp/vrrp_json.c, keepalived/vrrp/vrrp_parser.c, keepalived/vrrp/vrrp_print.c, keepalived/vrrp/vrrp_scheduler.c, lib/logger.c, lib/memory.c, lib/notify.c, lib/parser.c, lib/utils.c, lib/utils.h
Issue #1048 identified these problems which are now fixed.
=> Allow limiting file access permissions for created files, and don't allow overwriting of systems files via symbolic links

.travis.yml, configure.ac, keepalived/bfd/bfd_daemon.c, keepalived/check/check_daemon.c, keepalived/check/ipvswrapper.c, keepalived/core/daemon.c, keepalived/core/main.c, keepalived/vrrp/vrrp_daemon.c, lib/logger.c, lib/logger.h, lib/memory.c, lib/notify.c, lib/utils.c
This should fully resolve CVE-2018-19046.
=> Ensure log/data files written by keepalived cannot be read by non root user

keepalived/check/check_snmp.c, keepalived/core/snmp.c, keepalived/vrrp/vrrp_snmp.c, lib/scheduler.c, lib/utils.c
=> Fix segfault when shutting down when snmp activity occurs

.travis.yml, configure.ac, keepalived/bfd/bfd.c, keepalived/bfd/bfd_data.c, keepalived/bfd/bfd_event.c, keepalived/bfd/bfd_parser.c, keepalived/bfd/bfd_scheduler.c, keepalived/core/keepalived_netlink.c, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_if.c, keepalived/vrrp/vrrp_if_config.c, lib/Makefile.am, lib/assert_debug.h, lib/memory.c, lib/scheduler.c, lib/signals.c
=> Update receive buffer size if an interface is created with a larger MTU

configure.ac, keepalived/core/global_data.c
Issue #1071 identified a segfault when configuring SMTP alerts
=> Fix segfault when smtp alerts configured

doc/KEEPALIVED-MIB.txt, doc/man/man5/keepalived.conf.5, keepalived/check/check_api.c, keepalived/check/check_data.c, keepalived/check/check_parser.c, keepalived/check/check_snmp.c, keepalived/include/check_data.h, lib/parser.c
This patches are based on the patch submitted by @tamutamu in pull request #1126.
=> Make it possible to specify decimal value for warmup, delay_loop, connect_timeout, delay_before_retry.

keepalived/check/check_api.c, keepalived/check/check_parser.c, lib/parser.c, lib/timer.h
It enable to set greater than or equal to zero value as Mintime for delay_loop, connect_timeout.
=> It enable to set zero value as mintime for delay_loop and connect_timeout.

keepalived/core/track_process.c
=> Fix segfault in handle_proc_ev()

configure.ac, keepalived/check/check_ssl.c
=> Fix OpenSSL init failure with OpenSSL v1.1.1

configure.ac, genhash/ssl.c, keepalived/check/check_api.c, keepalived/check/check_data.c, keepalived/check/check_dns.c, keepalived/check/check_http.c, keepalived/check/check_ssl.c, keepalived/check/check_tcp.c, keepalived/check/ipwrapper.c, keepalived/include/check_data.h, keepalived/include/check_dns.h, keepalived/include/check_http.h, keepalived/include/check_tcp.h, lib/utils.c, lib/utils.h
Further resolutions for issue #1151.
=> Update OPENSSL_init_crypto() workaround 

configure.ac, keepalived/check/Makefile.am, keepalived/check/check_api.c, keepalived/check/check_daemon.c, keepalived/check/check_data.c, keepalived/check/check_dns.c, keepalived/check/check_print.c, keepalived/check/check_tcp.c, keepalived/core/main.c, keepalived/include/check_data.h, keepalived/include/check_print.h
=> Fix alpha mode checkers at reload

lib/logger.c
This pull request superceeds pull request #1149.
=> Fix calling syslog when not using signalfd()

keepalived/check/check_data.c, keepalived/check/ipwrapper.c
This should resolve issue #1163.
=> Fix real server checkers moving from failed to OK on reload

keepalived/include/vrrp.h, keepalived/vrrp/vrrp_notify.c, lib/signals.c
=> Ensure initial notifies are sent for vrrp instances in a sync group

configure.ac, doc/man/man5/keepalived.conf.5, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/include/global_data.h, keepalived/vrrp/vrrp_daemon.c
=> Add vrrp_startup_delay configuration option

configure.ac, keepalived.spec.in, keepalived/check/check_misc.c
=> Fix rpmbuild on CentOS 7

genhash/http.c, genhash/layer4.c, keepalived/bfd/bfd_scheduler.c, keepalived/check/check_bfd.c, keepalived/check/check_dns.c, keepalived/check/check_http.c, keepalived/check/check_smtp.c, keepalived/check/check_ssl.c, keepalived/core/keepalived_netlink.c, keepalived/core/layer4.c, keepalived/core/smtp.c, keepalived/core/track_process.c, keepalived/vrrp/vrrp_dbus.c, keepalived/vrrp/vrrp_scheduler.c, keepalived/vrrp/vrrp_track.c, lib/scheduler.c, lib/scheduler.h, lib/signals.c
=> Close checker and smtp_alert sockets on reload

doc/man/man5/keepalived.conf.5, keepalived/check/check_data.c, keepalived/check/check_parser.c, keepalived/check/ipvswrapper.c, keepalived/include/check_data.h, lib/utils.c, lib/utils.h
=> Allow real and sorry servers to specify port 0 or no port, and add VS/RS port validation

configure.ac, keepalived/check/check_http.c
=> Make configure work properly when system not using systemd

keepalived/vrrp/vrrp_iprule.c
=> Typo writing word error fix

doc/man/man5/keepalived.conf.5, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/include/global_data.h, keepalived/include/vrrp.h, keepalived/include/vrrp_notify.h, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_notify.c, keepalived/vrrp/vrrp_parser.c, keepalived/vrrp/vrrp_track.c, lib/notify.c, lib/notify.h
The addition of notifications of priority changes was requested in issue #1213.
=> Add notification via FIFOs only of VRRP instance priority changes

doc/man/man5/keepalived.conf.5
Fix typo grammar error.
Make it bold.
=> Fix promote_secondaries

keepalived/check/check_data.c, keepalived/check/ipvswrapper.c, keepalived/check/ipwrapper.c, keepalived/include/check_data.h, lib/notify.c, lib/notify.h, lib/utils.c, lib/utils.h
These commits resolve issue #1226.
=> Resolve removing virtual servers in virtual server group after reload

keepalived/vrrp/vrrp_daemon.c, keepalived/vrrp/vrrp_dbus.c
This is an initial set of fixes. There are still more issues to be resolved, but this might resolve the segfault for issue #1239.
=> Various DBus reload fixes

configure.ac, doc/man/man5/keepalived.conf.5, keepalived/core/keepalived_netlink.c, keepalived/include/vrrp_ip_rule_route_parser.h, keepalived/include/vrrp_iproute.h, keepalived/vrrp/vrrp_data.c, keepalived/vrrp/vrrp_ip_rule_route_parser.c
=> Fix building snaps

LICENSE
Since this is somewhat out of norm having to do for a repo and there seem to be keepalived forks under different license on github best to clarify this stuff hence this pull request but I have to ask. 
Is this your own personal account and this is fork of keepalived with upstream being hosted somewhere else or is this the upstream keepalived repository?  ( the repo also lacks typical release and test stuff for upstream project ) 
If this is upstream why did you chose to have it under your personal account but not under it's own project account on github ( sorry was going to ask on the ~mailinglist~ but had to do some weird steps and create account on a site called groups.io which needed approval to be able to join the discussion forum for the project ).
=> Add a proper license file

keepalived/core/smtp.c, keepalived/include/smtp.h
=> Fix setting up of SMTP headers

keepalived/vrrp/vrrp_scheduler.c
This incorporates the patch in pull request #1310.
=> Fix false-positive send_instance_notifies calls

configure.ac, doc/KEEPALIVED-MIB.txt, doc/man/man5/keepalived.conf.5, keepalived/check/check_data.c, keepalived/check/check_http.c, keepalived/check/check_parser.c, keepalived/check/check_snmp.c, keepalived/check/ipvswrapper.c, keepalived/check/ipwrapper.c, keepalived/check/libipvs.c, keepalived/include/check_data.h, keepalived/include/ip_vs.h
The individual commits identify the patch requirements for ipvsadm to be able to view the new configuration.
=> Add support for IPVS GUE and GRE tunnels

doc/man/man8/keepalived.8.in
Had to figure this out today, would've been useful to have this documented.
Signed-off-by: Sam Varshavchik <mrsam@courier-mta.com>
=> Include firewalld documentation.

keepalived/check/ipwrapper.c
**Disclaimer**
I know I am using `sorry_server` feature in wrong way, but since I spent some time with debugging I want to share my findings and I believe even discussion could be helpful for the project.
**Issue**
When there is virtual server configuration with `sorry_server` exactly same like one of `real_server`, service is unable to recover properly during transition from sorry server stage back when "twin" `real_server` comes up first.
Keepalived simply failed to add `real_server` because of duplicity in IPVS, but thinks everything is OK.
I am using this setup to mitigate complete out of service when backend health checks are implemented incorrectly.
**My solution**
I can see two minor caveants in my solution:
* When `inhibit_on_failure` is used for real servers it has to be used for …
=> Change order of IPVS commands on quorum change

keepalived/check/check_daemon.c, keepalived/vrrp/vrrp_daemon.c
=> Make SNMP work after a reload

lib/Makefile.am
This will be reverted after the snap build has completed.
=> Test: find out why snaps always have a '+' in the version

doc/man/man5/keepalived.conf.5
I found some format problem in new document, such as:
1.  Four propertys' name aren't be bold.
2.  Some indentations are Tabs instead of spaces, resulting in inconsistent display.
3.  Some spaces of indentations whose quantity is not 4 but 2. 
So I try to fix it.
=> Fix some format of new document

snap/snapcraft.yaml
=> snap: Further snap build testing

keepalived/core/global_parser.c
because  donnot know which is reasonable. I commit for each one.
and each commit log has my understanding.
thanks for your time.
these new min values , are same as keepalived/manpage ,and same as ipvsadm.
=> change same lvs_sync_daemon keys range

keepalived/check/check_dns.c
=> dns checker will never print "after n retries"

configure.ac, keepalived/vrrp/vrrp_nftables.c
=> vrrp: Fix building on Linux 3.15 with nftables support

doc/man/man5/keepalived.conf.5
There is no HTTP_CHECK / SSL_CHECK
=> Fix doc for retry default value for HTTP checks

keepalived/include/vrrp_iproute.h, keepalived/vrrp/vrrp.c, keepalived/vrrp/vrrp_daemon.c, keepalived/vrrp/vrrp_iproute.c
=> vrrp: ensure virtual routes are not lost during a reload

keepalived/core/daemon.c, keepalived/core/main.c, keepalived/include/daemon.h, lib/notify.c, lib/notify.h, lib/process.c, lib/process.h, lib/signals.c, lib/signals.h, lib/utils.c
Issue #1714 raised a question of resetting priority not working properly before invoking scripts. The code was actually redundant but it lead to this series of commits to streamline and simplify the code.
=> Streamline some code around invoking scripts

keepalived/core/main.c
Change "build" => "built" for past tense.
=> Fix minor grammar error

doc/man/man5/keepalived.conf.5, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/core/main.c, keepalived/include/global_data.h, keepalived/vrrp/vrrp_daemon.c, lib/bitops.h, lib/memory.c, lib/parser.c, lib/parser.h, lib/scheduler.c, lib/scheduler.h
This is based on the work by @wangxp006.
=> Add reload_check_config configuration option

keepalived/check/ipwrapper.c
when rs offline,the log description is not appropriate
=> optimize rs online and offline log print

doc/man/man5/keepalived.conf.5.in
Seems leftover from a reformatting/reflowing of the comments
=> Remove stray hash character

README.kernel_versions, doc/man/man5/keepalived.conf.5.in, keepalived/bfd/bfd_daemon.c, keepalived/bfd/bfd_data.c, keepalived/check/check_daemon.c, keepalived/core/config_notify.c, keepalived/core/global_data.c, keepalived/core/global_parser.c, keepalived/include/bfd_data.h, keepalived/include/config_notify.h, keepalived/vrrp/vrrp_daemon.c, lib/parser.c, lib/parser.h
This is intended to help debugging reload problems
=> Add option for saving config and internal status before and after reloads

doc/samples/sample_notify_fifo.sh, lib/notify.c
Related to https://github.com/acassen/keepalived/pull/2030#issuecomment-959084710
=> Fix concurrent fifo

doc/samples/sample_notify_fifo.sh
When keepalived reloads its configuration, the notify FIFO script is
restarted. The script that was running before the reload does not end
immediately. Then the new one can run concurrently.
Note that although the ALRM trap is scheduled 500ms after the shutdown,
if a command is running when the 500ms period is over, the script waits
for the command end before calling stopping().
Use a PID file to avoid running concurrent instances of
sample_notify_fifo.sh. If the script exists without removing the PID
file, the new instance checks that no file descriptor is open for the
PID file with the PID that it contains. Checking that the PID does not
exist in the process list is not sufficient as a PID may be reused by
another process.
Signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
=> fifo: avoid concurrent instances of sample_notify_fifo.sh

keepalived/check/check_http.c, keepalived/check/check_parser.c
Solve the problems mentioned in the issue #2165
=> fix mem leaks when virtualhost is duplicate

keepalived/vrrp/vrrp_json.c
Hi, refered to: [#2247](https://github.com/acassen/keepalived/pull/2247); pulling again with fixes and more checks.
I also checked if output is corect when more then one ```track_process``` is defined and all seems to be ok.
Minimal KEEPALIVED configuration:
```
global_defs {
router_id R01
vrrp_version 3
vrrp_no_swap
vrrp_strict
}
vrrp_track_process asterisk {
process "asterisk"
}
vrrp_track_process gunicorn {
process "gunicorn"
}
vrrp_instance VI_1 {
interface eth0
virtual_router_id 99
nopreempt
state BACKUP
priority 233
advert_int 1
accept
virtual_ipaddress {
192.168.1.250 dev eth0
}
track_process {
asterisk
gunicorn
}
}
```
Getting data:
```
kill -s $(keepalived --signum=JSON) $(cat /run/keepalived/keepalived.pid)
```
JSON output:
```
[
{
"data": {
"iname": "VI_1", …
```
=> vrrp_json_track_process_dump

keepalived/core/keepalived_netlink.c
The user is not supposed to shutdown a vmac interface created by keepalived. However, it can mistakenly happen. When the link is re-established, the link-local has disappear (the kernel removes all IPv6 addresses on link down except if keep_addr_on_down sysctl is on) and sending VRRP packet is no nore possible.
Restore the IPv6 Link-Local after a VMAC interface flapping. A Link-Local is not set when the VRRP packets are sent from the base interface (vmac-xmit-base).
Note that the IPv6 Virtual Addresses are also removed on link down which is the desired behavior. Enabling keep_addr_on_down sysctl would keep the link-local without this patch but would break this behavior.
Original patch signed-off-by: Louis Scalbert <louis.scalbert@6wind.com>
Signed-off-by: Quentin Armitage …
=> vrrp: restore the vmac ipv6 link-local after flapping

keepalived/core/keepalived_netlink.c
route_is_ours() checked the outgoing interface for virtual routes but not for static routes. This commit now adds checking of the outgoing interface for static routes, and now moves the code to compare routes into a separate function used for both virtual and static routes.
=> vrrp: Check interface for static routes if deleted

keepalived/vrrp/vrrp_daemon.c
If keepalived reloaded its configuration before a specified vrrp_startup_delay had expired, the startup_delay was never being timed out, and so all received adverts would be discarded.
The commit caused the startup_delay timer to be reinstated after a reload if the timer has not yet expired.
=> vrrp: Handle a reload before vrrp_delayed_start has expired

lib/parser.c
It makes the code somewhat more comprehensible.
=> lib: used defined values for read_hex_str special characters
